services:
  postgres:
    image: postgres:16.10
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-numeraire}
      # Enable logging
      POSTGRES_LOGGING: "on"
      # Environment variables to control PostgreSQL logging behavior
      POSTGRES_LOG_MIN_DURATION_STATEMENT: "0" # Log all statements immediately
      POSTGRES_LOG_STATEMENTS: "all"
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "logging_collector=off" # Ensure logging collector is turned off to use stderr
      - "-c"
      - "log_statement=all" # Log all statements
      - "-c"
      - "log_destination=stderr" # Send logs to stderr

  pgadmin:
    image: dpage/pgadmin4:9.9
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_SERVER_JSON_FILE: /servers.json
    ports:
      - 5050:80
    volumes:
      - pgadmin:/root/.pgadmin
      - ./deps/pgadmin/servers.json:/servers.json
    depends_on:
      - postgres

  swissknife:
    image: swissknife:latest
    environment:
      SWISSKNIFE_DATABASE__URL: ${SWISSKNIFE_DATABASE__URL:-postgres://postgres:postgres@postgres/numeraire}
      SWISSKNIFE_CLN_REST_CONFIG__RUNE: ${SWISSKNIFE_CLN_REST_CONFIG__RUNE:-}
      SWISSKNIFE_JWT__SECRET: ${SWISSKNIFE_JWT__SECRET:-}
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./config/production.toml:/config/production.toml
volumes:
  db:
  pgadmin:
