domain: "numeraire.tech"
ln_provider: clngrpc
auth_provider: jwt

logging:
  format: compact
  ansi: true
  level: debug
  filter: swissknife=debug

oauth2:
  domain: "dev-z3xohtidpayxvzid.us.auth0.com"

web:
  addr: 0.0.0.0:3000
  request_timeout: 180s

cln_rest_config:
  endpoint: "http://127.0.0.1:8182"

cln_config:
  endpoint: "https://127.0.0.1:11002"
  certs_dir: "/Users/darioanongbavarela/.polar/networks/1/volumes/c-lightning/bob/lightningd/regtest"
