//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

use crate::domains::lightning::entities::LnAddress;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ln_address")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub user_id: String,
    #[sea_orm(unique)]
    pub username: String,
    pub active: bool,
    pub created_at: DateTimeUtc,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "crate::domains::invoices::adapters::InvoiceModel")]
    Invoice,
}

impl Related<crate::domains::invoices::adapters::InvoiceModel> for Entity {
    fn to() -> RelationDef {
        Relation::Invoice.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl From<Model> for LnAddress {
    fn from(model: Model) -> Self {
        LnAddress {
            id: model.id,
            user_id: model.user_id,
            username: model.username,
            active: model.active,
            created_at: model.created_at,
            updated_at: model.updated_at,
        }
    }
}
