// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import {
  createApiKeyResponseTransformer,
  createWalletApiKeyResponseTransformer,
  generateBtcAddressResponseTransformer,
  generateInvoiceResponseTransformer,
  getAddressResponseTransformer,
  getApiKeyResponseTransformer,
  getBtcAddressResponseTransformer,
  getInvoiceResponseTransformer,
  getPaymentResponseTransformer,
  getUserWalletResponseTransformer,
  getWalletAddressResponseTransformer,
  getWalletApiKeyResponseTransformer,
  getWalletInvoiceResponseTransformer,
  getWalletPaymentResponseTransformer,
  getWalletResponseTransformer,
  listAddressesResponseTransformer,
  listApiKeysResponseTransformer,
  listBtcAddressesResponseTransformer,
  listContactsResponseTransformer,
  listInvoicesResponseTransformer,
  listPaymentsResponseTransformer,
  listWalletApiKeysResponseTransformer,
  listWalletInvoicesResponseTransformer,
  listWalletOverviewsResponseTransformer,
  listWalletPaymentsResponseTransformer,
  listWalletsResponseTransformer,
  newWalletBtcAddressResponseTransformer,
  newWalletInvoiceResponseTransformer,
  payResponseTransformer,
  registerAddressResponseTransformer,
  registerWalletAddressResponseTransformer,
  registerWalletResponseTransformer,
  updateAddressResponseTransformer,
  updateWalletAddressResponseTransformer,
  walletPayResponseTransformer,
} from './transformers.gen';
import type {
  CallbackData,
  CallbackErrors,
  CallbackResponses,
  CreateApiKeyData,
  CreateApiKeyErrors,
  CreateApiKeyResponses,
  CreateWalletApiKeyData,
  CreateWalletApiKeyErrors,
  CreateWalletApiKeyResponses,
  DeleteAddressData,
  DeleteAddressErrors,
  DeleteAddressesData,
  DeleteAddressesErrors,
  DeleteAddressesResponses,
  DeleteAddressResponses,
  DeleteBtcAddressData,
  DeleteBtcAddressErrors,
  DeleteBtcAddressesData,
  DeleteBtcAddressesErrors,
  DeleteBtcAddressesResponses,
  DeleteBtcAddressResponses,
  DeleteExpiredInvoicesData,
  DeleteExpiredInvoicesErrors,
  DeleteExpiredInvoicesResponses,
  DeleteFailedPaymentsData,
  DeleteFailedPaymentsErrors,
  DeleteFailedPaymentsResponses,
  DeleteInvoiceData,
  DeleteInvoiceErrors,
  DeleteInvoiceResponses,
  DeleteInvoicesData,
  DeleteInvoicesErrors,
  DeleteInvoicesResponses,
  DeletePaymentData,
  DeletePaymentErrors,
  DeletePaymentResponses,
  DeletePaymentsData,
  DeletePaymentsErrors,
  DeletePaymentsResponses,
  DeleteWalletAddressData,
  DeleteWalletAddressErrors,
  DeleteWalletAddressResponses,
  DeleteWalletData,
  DeleteWalletErrors,
  DeleteWalletResponses,
  DeleteWalletsData,
  DeleteWalletsErrors,
  DeleteWalletsResponses,
  GenerateBtcAddressData,
  GenerateBtcAddressErrors,
  GenerateBtcAddressResponses,
  GenerateInvoiceData,
  GenerateInvoiceErrors,
  GenerateInvoiceResponses,
  GetAddressData,
  GetAddressErrors,
  GetAddressResponses,
  GetApiKeyData,
  GetApiKeyErrors,
  GetApiKeyResponses,
  GetBtcAddressData,
  GetBtcAddressErrors,
  GetBtcAddressResponses,
  GetInvoiceData,
  GetInvoiceErrors,
  GetInvoiceResponses,
  GetPaymentData,
  GetPaymentErrors,
  GetPaymentResponses,
  GetUserWalletData,
  GetUserWalletErrors,
  GetUserWalletResponses,
  GetWalletAddressData,
  GetWalletAddressErrors,
  GetWalletAddressResponses,
  GetWalletApiKeyData,
  GetWalletApiKeyErrors,
  GetWalletApiKeyResponses,
  GetWalletBalanceData,
  GetWalletBalanceErrors,
  GetWalletBalanceResponses,
  GetWalletData,
  GetWalletErrors,
  GetWalletInvoiceData,
  GetWalletInvoiceErrors,
  GetWalletInvoiceResponses,
  GetWalletPaymentData,
  GetWalletPaymentErrors,
  GetWalletPaymentResponses,
  GetWalletResponses,
  HealthCheckData,
  HealthCheckErrors,
  HealthCheckResponses,
  ListAddressesData,
  ListAddressesErrors,
  ListAddressesResponses,
  ListApiKeysData,
  ListApiKeysErrors,
  ListApiKeysResponses,
  ListBtcAddressesData,
  ListBtcAddressesErrors,
  ListBtcAddressesResponses,
  ListContactsData,
  ListContactsErrors,
  ListContactsResponses,
  ListInvoicesData,
  ListInvoicesErrors,
  ListInvoicesResponses,
  ListPaymentsData,
  ListPaymentsErrors,
  ListPaymentsResponses,
  ListWalletApiKeysData,
  ListWalletApiKeysErrors,
  ListWalletApiKeysResponses,
  ListWalletInvoicesData,
  ListWalletInvoicesErrors,
  ListWalletInvoicesResponses,
  ListWalletOverviewsData,
  ListWalletOverviewsErrors,
  ListWalletOverviewsResponses,
  ListWalletPaymentsData,
  ListWalletPaymentsErrors,
  ListWalletPaymentsResponses,
  ListWalletsData,
  ListWalletsErrors,
  ListWalletsResponses,
  MarkWelcomeCompleteData,
  MarkWelcomeCompleteErrors,
  MarkWelcomeCompleteResponses,
  NewWalletBtcAddressData,
  NewWalletBtcAddressErrors,
  NewWalletBtcAddressResponses,
  NewWalletInvoiceData,
  NewWalletInvoiceErrors,
  NewWalletInvoiceResponses,
  PayData,
  PayErrors,
  PayResponses,
  ReadinessCheckData,
  ReadinessCheckResponses,
  RegisterAddressData,
  RegisterAddressErrors,
  RegisterAddressResponses,
  RegisterWalletAddressData,
  RegisterWalletAddressErrors,
  RegisterWalletAddressResponses,
  RegisterWalletData,
  RegisterWalletErrors,
  RegisterWalletResponses,
  RevokeApiKeyData,
  RevokeApiKeyErrors,
  RevokeApiKeyResponses,
  RevokeApiKeysData,
  RevokeApiKeysErrors,
  RevokeApiKeysResponses,
  RevokeWalletApiKeyData,
  RevokeWalletApiKeyErrors,
  RevokeWalletApiKeyResponses,
  RevokeWalletApiKeysData,
  RevokeWalletApiKeysErrors,
  RevokeWalletApiKeysResponses,
  SetupCheckData,
  SetupCheckErrors,
  SetupCheckResponses,
  SignInData,
  SignInErrors,
  SignInResponses,
  SignUpData,
  SignUpErrors,
  SignUpResponses,
  UpdateAddressData,
  UpdateAddressErrors,
  UpdateAddressResponses,
  UpdateWalletAddressData,
  UpdateWalletAddressErrors,
  UpdateWalletAddressResponses,
  VersionCheckData,
  VersionCheckResponses,
  WalletPayData,
  WalletPayErrors,
  WalletPayResponses,
  WellKnownData,
  WellKnownErrors,
  WellKnownNostrData,
  WellKnownNostrErrors,
  WellKnownNostrResponses,
  WellKnownResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Well-known endpoint
 *
 * Returns the LNURL payRequest for this LN Address (username). The returned payload contains information allowing the payer to generate an invoice. See [LUDS-06](https://github.com/lnurl/luds/blob/luds/06.md)
 */
export const wellKnown = <ThrowOnError extends boolean = false>(
  options: Options<WellKnownData, ThrowOnError>
): RequestResult<WellKnownResponses, WellKnownErrors, ThrowOnError> =>
  (options.client ?? client).get<WellKnownResponses, WellKnownErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/.well-known/lnurlp/{username}',
    ...options,
  });

/**
 * Well-known endpoint
 *
 * Returns the names known by this service given username. The returned payload contains public keys in hex format. See [NIP-05](https://github.com/nostr-protocol/nips/blob/master/05.md)
 */
export const wellKnownNostr = <ThrowOnError extends boolean = false>(
  options?: Options<WellKnownNostrData, ThrowOnError>
): RequestResult<WellKnownNostrResponses, WellKnownNostrErrors, ThrowOnError> =>
  (options?.client ?? client).get<WellKnownNostrResponses, WellKnownNostrErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/.well-known/nostr.json',
    ...options,
  });

/**
 * LNURL callback endpoint
 *
 * Returns the callback response for this LN Address (username). Containing an invoice and information on how to behave upon success. See [LUDS-06](https://github.com/lnurl/luds/blob/luds/06.md)
 */
export const callback = <ThrowOnError extends boolean = false>(
  options: Options<CallbackData, ThrowOnError>
): RequestResult<CallbackResponses, CallbackErrors, ThrowOnError> =>
  (options.client ?? client).get<CallbackResponses, CallbackErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/lnurlp/{username}/callback',
    ...options,
  });

/**
 * Revoke API Keys
 *
 * Revokes all the API Keys given a filter. Returns the number of revoked keys.
 */
export const revokeApiKeys = <ThrowOnError extends boolean = false>(
  options?: Options<RevokeApiKeysData, ThrowOnError>
): RequestResult<RevokeApiKeysResponses, RevokeApiKeysErrors, ThrowOnError> =>
  (options?.client ?? client).delete<RevokeApiKeysResponses, RevokeApiKeysErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/api-keys',
    ...options,
  });

/**
 * List API Keys
 *
 * Returns all the API Keys given a filter
 */
export const listApiKeys = <ThrowOnError extends boolean = false>(
  options?: Options<ListApiKeysData, ThrowOnError>
): RequestResult<ListApiKeysResponses, ListApiKeysErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListApiKeysResponses, ListApiKeysErrors, ThrowOnError>({
    responseTransformer: listApiKeysResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/api-keys',
    ...options,
  });

/**
 * Generate a new API Key
 *
 * Returns the generated API Key for the given user. Users can create API keys with permissions as a subset of his current permissions.
 */
export const createApiKey = <ThrowOnError extends boolean = false>(
  options: Options<CreateApiKeyData, ThrowOnError>
): RequestResult<CreateApiKeyResponses, CreateApiKeyErrors, ThrowOnError> =>
  (options.client ?? client).post<CreateApiKeyResponses, CreateApiKeyErrors, ThrowOnError>({
    responseTransformer: createApiKeyResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/api-keys',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Revoke an API Key
 *
 * Revokes an API Key by ID. Returns an empty body.
 */
export const revokeApiKey = <ThrowOnError extends boolean = false>(
  options: Options<RevokeApiKeyData, ThrowOnError>
): RequestResult<RevokeApiKeyResponses, RevokeApiKeyErrors, ThrowOnError> =>
  (options.client ?? client).delete<RevokeApiKeyResponses, RevokeApiKeyErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/api-keys/{id}',
    ...options,
  });

/**
 * Find an API Key
 *
 * Returns the API Key by its ID.
 */
export const getApiKey = <ThrowOnError extends boolean = false>(
  options: Options<GetApiKeyData, ThrowOnError>
): RequestResult<GetApiKeyResponses, GetApiKeyErrors, ThrowOnError> =>
  (options.client ?? client).get<GetApiKeyResponses, GetApiKeyErrors, ThrowOnError>({
    responseTransformer: getApiKeyResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/api-keys/{id}',
    ...options,
  });

/**
 * Sign In
 *
 * Returns a JWT token to be used for authentication. The JWT token contains authentication and permissions. Sign in is only available for `JWT` Auth provider.
 */
export const signIn = <ThrowOnError extends boolean = false>(
  options: Options<SignInData, ThrowOnError>
): RequestResult<SignInResponses, SignInErrors, ThrowOnError> =>
  (options.client ?? client).post<SignInResponses, SignInErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/auth/sign-in',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Sign up
 *
 * Creates the initial Admin user. Returns a JWT token to be used for authentication. The JWT token contains authentication and permissions. Sign up is only available for `JWT` Auth provider.
 */
export const signUp = <ThrowOnError extends boolean = false>(
  options: Options<SignUpData, ThrowOnError>
): RequestResult<SignUpResponses, SignUpErrors, ThrowOnError> =>
  (options.client ?? client).post<SignUpResponses, SignUpErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/auth/sign-up',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Bitcoin addresses
 *
 * Deletes all the Bitcoin addresses given a filter. Returns the number of deleted addresses. Deleting an address can have an effect on the user balance
 */
export const deleteBtcAddresses = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteBtcAddressesData, ThrowOnError>
): RequestResult<DeleteBtcAddressesResponses, DeleteBtcAddressesErrors, ThrowOnError> =>
  (options?.client ?? client).delete<
    DeleteBtcAddressesResponses,
    DeleteBtcAddressesErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/bitcoin/addresses',
    ...options,
  });

/**
 * List Bitcoin addresses
 *
 * Returns all the Bitcoin addresses given a filter
 */
export const listBtcAddresses = <ThrowOnError extends boolean = false>(
  options?: Options<ListBtcAddressesData, ThrowOnError>
): RequestResult<ListBtcAddressesResponses, ListBtcAddressesErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListBtcAddressesResponses, ListBtcAddressesErrors, ThrowOnError>({
    responseTransformer: listBtcAddressesResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/bitcoin/addresses',
    ...options,
  });

/**
 * Generate a new Bitcoin address
 *
 * Returns the generated Bitcoin address for the given user
 */
export const generateBtcAddress = <ThrowOnError extends boolean = false>(
  options: Options<GenerateBtcAddressData, ThrowOnError>
): RequestResult<GenerateBtcAddressResponses, GenerateBtcAddressErrors, ThrowOnError> =>
  (options.client ?? client).post<
    GenerateBtcAddressResponses,
    GenerateBtcAddressErrors,
    ThrowOnError
  >({
    responseTransformer: generateBtcAddressResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/bitcoin/addresses',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a Bitcoin address
 *
 * Deletes an Bitcoin address by ID. Returns an empty body. Deleting a Bitcoin address has an effect on the user balance
 */
export const deleteBtcAddress = <ThrowOnError extends boolean = false>(
  options: Options<DeleteBtcAddressData, ThrowOnError>
): RequestResult<DeleteBtcAddressResponses, DeleteBtcAddressErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteBtcAddressResponses,
    DeleteBtcAddressErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/bitcoin/addresses/{id}',
    ...options,
  });

/**
 * Find a Bitcoin address
 *
 * Returns the Bitcoin address by its ID.
 */
export const getBtcAddress = <ThrowOnError extends boolean = false>(
  options: Options<GetBtcAddressData, ThrowOnError>
): RequestResult<GetBtcAddressResponses, GetBtcAddressErrors, ThrowOnError> =>
  (options.client ?? client).get<GetBtcAddressResponses, GetBtcAddressErrors, ThrowOnError>({
    responseTransformer: getBtcAddressResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/bitcoin/addresses/{id}',
    ...options,
  });

/**
 * Delete invoices
 *
 * Deletes all the invoices given a filter. Returns the number of deleted invoices. Deleting an invoice can have an effect on the user balance
 */
export const deleteInvoices = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteInvoicesData, ThrowOnError>
): RequestResult<DeleteInvoicesResponses, DeleteInvoicesErrors, ThrowOnError> =>
  (options?.client ?? client).delete<DeleteInvoicesResponses, DeleteInvoicesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/invoices',
    ...options,
  });

/**
 * List invoices
 *
 * Returns all the invoices given a filter
 */
export const listInvoices = <ThrowOnError extends boolean = false>(
  options?: Options<ListInvoicesData, ThrowOnError>
): RequestResult<ListInvoicesResponses, ListInvoicesErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListInvoicesResponses, ListInvoicesErrors, ThrowOnError>({
    responseTransformer: listInvoicesResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/invoices',
    ...options,
  });

/**
 * Generate a new invoice
 *
 * Returns the generated invoice for the given user
 */
export const generateInvoice = <ThrowOnError extends boolean = false>(
  options: Options<GenerateInvoiceData, ThrowOnError>
): RequestResult<GenerateInvoiceResponses, GenerateInvoiceErrors, ThrowOnError> =>
  (options.client ?? client).post<GenerateInvoiceResponses, GenerateInvoiceErrors, ThrowOnError>({
    responseTransformer: generateInvoiceResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/invoices',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete an invoice
 *
 * Deletes an invoice by ID. Returns an empty body. Deleting an invoice has an effect on the user balance
 */
export const deleteInvoice = <ThrowOnError extends boolean = false>(
  options: Options<DeleteInvoiceData, ThrowOnError>
): RequestResult<DeleteInvoiceResponses, DeleteInvoiceErrors, ThrowOnError> =>
  (options.client ?? client).delete<DeleteInvoiceResponses, DeleteInvoiceErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/invoices/{id}',
    ...options,
  });

/**
 * Find an invoice
 *
 * Returns the invoice by its ID.
 */
export const getInvoice = <ThrowOnError extends boolean = false>(
  options: Options<GetInvoiceData, ThrowOnError>
): RequestResult<GetInvoiceResponses, GetInvoiceErrors, ThrowOnError> =>
  (options.client ?? client).get<GetInvoiceResponses, GetInvoiceErrors, ThrowOnError>({
    responseTransformer: getInvoiceResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/invoices/{id}',
    ...options,
  });

/**
 * Delete LN Addresses
 *
 * Deletes all the addresses given a filter. Returns the number of deleted addresses
 */
export const deleteAddresses = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteAddressesData, ThrowOnError>
): RequestResult<DeleteAddressesResponses, DeleteAddressesErrors, ThrowOnError> =>
  (options?.client ?? client).delete<DeleteAddressesResponses, DeleteAddressesErrors, ThrowOnError>(
    {
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/v1/lightning-addresses',
      ...options,
    }
  );

/**
 * List LN Addresses
 *
 * Returns all the addresses given a filter
 */
export const listAddresses = <ThrowOnError extends boolean = false>(
  options?: Options<ListAddressesData, ThrowOnError>
): RequestResult<ListAddressesResponses, ListAddressesErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListAddressesResponses, ListAddressesErrors, ThrowOnError>({
    responseTransformer: listAddressesResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/lightning-addresses',
    ...options,
  });

/**
 * Register a new LN Address
 *
 * Registers an address. Returns the address details. LN Addresses are ready to receive funds through the LNURL protocol upon registration.
 */
export const registerAddress = <ThrowOnError extends boolean = false>(
  options: Options<RegisterAddressData, ThrowOnError>
): RequestResult<RegisterAddressResponses, RegisterAddressErrors, ThrowOnError> =>
  (options.client ?? client).post<RegisterAddressResponses, RegisterAddressErrors, ThrowOnError>({
    responseTransformer: registerAddressResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/lightning-addresses',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a LN Address
 *
 * Deletes an address by ID. Returns an empty body
 */
export const deleteAddress = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAddressData, ThrowOnError>
): RequestResult<DeleteAddressResponses, DeleteAddressErrors, ThrowOnError> =>
  (options.client ?? client).delete<DeleteAddressResponses, DeleteAddressErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/lightning-addresses/{id}',
    ...options,
  });

/**
 * Find a LN Address
 *
 * Returns the address by its ID.
 */
export const getAddress = <ThrowOnError extends boolean = false>(
  options: Options<GetAddressData, ThrowOnError>
): RequestResult<GetAddressResponses, GetAddressErrors, ThrowOnError> =>
  (options.client ?? client).get<GetAddressResponses, GetAddressErrors, ThrowOnError>({
    responseTransformer: getAddressResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/lightning-addresses/{id}',
    ...options,
  });

/**
 * Update a LN Address
 *
 * Updates an address. Returns the address details.
 */
export const updateAddress = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAddressData, ThrowOnError>
): RequestResult<UpdateAddressResponses, UpdateAddressErrors, ThrowOnError> =>
  (options.client ?? client).put<UpdateAddressResponses, UpdateAddressErrors, ThrowOnError>({
    responseTransformer: updateAddressResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/lightning-addresses/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get wallet
 *
 * Returns the user wallet.
 */
export const getUserWallet = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserWalletData, ThrowOnError>
): RequestResult<GetUserWalletResponses, GetUserWalletErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetUserWalletResponses, GetUserWalletErrors, ThrowOnError>({
    responseTransformer: getUserWalletResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me',
    ...options,
  });

/**
 * Revoke API Keys
 *
 * Revokes all the API Keys given a filter. Returns the number of revoked keys.
 */
export const revokeWalletApiKeys = <ThrowOnError extends boolean = false>(
  options?: Options<RevokeWalletApiKeysData, ThrowOnError>
): RequestResult<RevokeWalletApiKeysResponses, RevokeWalletApiKeysErrors, ThrowOnError> =>
  (options?.client ?? client).delete<
    RevokeWalletApiKeysResponses,
    RevokeWalletApiKeysErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/api-keys',
    ...options,
  });

/**
 * List API Keys
 *
 * Returns all the API Keys given a filter
 */
export const listWalletApiKeys = <ThrowOnError extends boolean = false>(
  options?: Options<ListWalletApiKeysData, ThrowOnError>
): RequestResult<ListWalletApiKeysResponses, ListWalletApiKeysErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListWalletApiKeysResponses,
    ListWalletApiKeysErrors,
    ThrowOnError
  >({
    responseTransformer: listWalletApiKeysResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/api-keys',
    ...options,
  });

/**
 * Generate a new API Key
 *
 * Returns the generated API Key for the given user. Users can create API keys with permissions as a subset of his current permissions.
 */
export const createWalletApiKey = <ThrowOnError extends boolean = false>(
  options: Options<CreateWalletApiKeyData, ThrowOnError>
): RequestResult<CreateWalletApiKeyResponses, CreateWalletApiKeyErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateWalletApiKeyResponses,
    CreateWalletApiKeyErrors,
    ThrowOnError
  >({
    responseTransformer: createWalletApiKeyResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/api-keys',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Revoke an API Key
 *
 * Revokes an API Key by ID. Returns an empty body.
 */
export const revokeWalletApiKey = <ThrowOnError extends boolean = false>(
  options: Options<RevokeWalletApiKeyData, ThrowOnError>
): RequestResult<RevokeWalletApiKeyResponses, RevokeWalletApiKeyErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    RevokeWalletApiKeyResponses,
    RevokeWalletApiKeyErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/api-keys/{id}',
    ...options,
  });

/**
 * Find an API Key
 *
 * Returns the API Key by its ID.
 */
export const getWalletApiKey = <ThrowOnError extends boolean = false>(
  options: Options<GetWalletApiKeyData, ThrowOnError>
): RequestResult<GetWalletApiKeyResponses, GetWalletApiKeyErrors, ThrowOnError> =>
  (options.client ?? client).get<GetWalletApiKeyResponses, GetWalletApiKeyErrors, ThrowOnError>({
    responseTransformer: getWalletApiKeyResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/api-keys/{id}',
    ...options,
  });

/**
 * Get wallet balance
 *
 * Returns the wallet balance.
 */
export const getWalletBalance = <ThrowOnError extends boolean = false>(
  options?: Options<GetWalletBalanceData, ThrowOnError>
): RequestResult<GetWalletBalanceResponses, GetWalletBalanceErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetWalletBalanceResponses, GetWalletBalanceErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/balance',
    ...options,
  });

/**
 * Generate a new Bitcoin address.
 *
 * Returns the Bitcoin address for the given address type. The returned address is the same until used.
 */
export const newWalletBtcAddress = <ThrowOnError extends boolean = false>(
  options: Options<NewWalletBtcAddressData, ThrowOnError>
): RequestResult<NewWalletBtcAddressResponses, NewWalletBtcAddressErrors, ThrowOnError> =>
  (options.client ?? client).post<
    NewWalletBtcAddressResponses,
    NewWalletBtcAddressErrors,
    ThrowOnError
  >({
    responseTransformer: newWalletBtcAddressResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/bitcoin/address',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List contacts
 *
 * Returns all the contacts
 */
export const listContacts = <ThrowOnError extends boolean = false>(
  options?: Options<ListContactsData, ThrowOnError>
): RequestResult<ListContactsResponses, ListContactsErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListContactsResponses, ListContactsErrors, ThrowOnError>({
    responseTransformer: listContactsResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/contacts',
    ...options,
  });

/**
 * Delete expired invoices
 *
 * Deletes all the invoices with status `Èxpired`. Returns the number of deleted invoices
 */
export const deleteExpiredInvoices = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteExpiredInvoicesData, ThrowOnError>
): RequestResult<DeleteExpiredInvoicesResponses, DeleteExpiredInvoicesErrors, ThrowOnError> =>
  (options?.client ?? client).delete<
    DeleteExpiredInvoicesResponses,
    DeleteExpiredInvoicesErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/invoices',
    ...options,
  });

/**
 * List invoices
 *
 * Returns all the invoices given a filter
 */
export const listWalletInvoices = <ThrowOnError extends boolean = false>(
  options?: Options<ListWalletInvoicesData, ThrowOnError>
): RequestResult<ListWalletInvoicesResponses, ListWalletInvoicesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListWalletInvoicesResponses,
    ListWalletInvoicesErrors,
    ThrowOnError
  >({
    responseTransformer: listWalletInvoicesResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/invoices',
    ...options,
  });

/**
 * Generate a new invoice
 *
 * Returns the generated invoice
 */
export const newWalletInvoice = <ThrowOnError extends boolean = false>(
  options: Options<NewWalletInvoiceData, ThrowOnError>
): RequestResult<NewWalletInvoiceResponses, NewWalletInvoiceErrors, ThrowOnError> =>
  (options.client ?? client).post<NewWalletInvoiceResponses, NewWalletInvoiceErrors, ThrowOnError>({
    responseTransformer: newWalletInvoiceResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/invoices',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Find an invoice
 *
 * Returns the invoice by its ID
 */
export const getWalletInvoice = <ThrowOnError extends boolean = false>(
  options: Options<GetWalletInvoiceData, ThrowOnError>
): RequestResult<GetWalletInvoiceResponses, GetWalletInvoiceErrors, ThrowOnError> =>
  (options.client ?? client).get<GetWalletInvoiceResponses, GetWalletInvoiceErrors, ThrowOnError>({
    responseTransformer: getWalletInvoiceResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/invoices/{id}',
    ...options,
  });

/**
 * Delete LN Address
 *
 * Deletes an address. Returns an empty body. Once the address is deleted, it will no longer be able to receive funds and its username can be claimed by another user.
 */
export const deleteWalletAddress = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteWalletAddressData, ThrowOnError>
): RequestResult<DeleteWalletAddressResponses, DeleteWalletAddressErrors, ThrowOnError> =>
  (options?.client ?? client).delete<
    DeleteWalletAddressResponses,
    DeleteWalletAddressErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/lightning-address',
    ...options,
  });

/**
 * Get LN Address
 *
 * Returns the registered address
 */
export const getWalletAddress = <ThrowOnError extends boolean = false>(
  options?: Options<GetWalletAddressData, ThrowOnError>
): RequestResult<GetWalletAddressResponses, GetWalletAddressErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetWalletAddressResponses, GetWalletAddressErrors, ThrowOnError>({
    responseTransformer: getWalletAddressResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/lightning-address',
    ...options,
  });

/**
 * Register LN Address
 *
 * Registers an address. Returns the address details. LN Addresses are ready to receive funds through the LNURL protocol upon registration.
 */
export const registerWalletAddress = <ThrowOnError extends boolean = false>(
  options: Options<RegisterWalletAddressData, ThrowOnError>
): RequestResult<RegisterWalletAddressResponses, RegisterWalletAddressErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RegisterWalletAddressResponses,
    RegisterWalletAddressErrors,
    ThrowOnError
  >({
    responseTransformer: registerWalletAddressResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/lightning-address',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update LN Address
 *
 * Updates the address. Returns the address details.
 */
export const updateWalletAddress = <ThrowOnError extends boolean = false>(
  options: Options<UpdateWalletAddressData, ThrowOnError>
): RequestResult<UpdateWalletAddressResponses, UpdateWalletAddressErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateWalletAddressResponses,
    UpdateWalletAddressErrors,
    ThrowOnError
  >({
    responseTransformer: updateWalletAddressResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/lightning-address',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete failed payments
 *
 * Deletes all the payments with `Failed` status. Returns the number of deleted payments
 */
export const deleteFailedPayments = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteFailedPaymentsData, ThrowOnError>
): RequestResult<DeleteFailedPaymentsResponses, DeleteFailedPaymentsErrors, ThrowOnError> =>
  (options?.client ?? client).delete<
    DeleteFailedPaymentsResponses,
    DeleteFailedPaymentsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/payments',
    ...options,
  });

/**
 * List payments
 *
 * Returns all the payments given a filter
 */
export const listWalletPayments = <ThrowOnError extends boolean = false>(
  options?: Options<ListWalletPaymentsData, ThrowOnError>
): RequestResult<ListWalletPaymentsResponses, ListWalletPaymentsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListWalletPaymentsResponses,
    ListWalletPaymentsErrors,
    ThrowOnError
  >({
    responseTransformer: listWalletPaymentsResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/payments',
    ...options,
  });

/**
 * Send payment
 *
 * Pay for a LN invoice, LNURL, LN Address, On-chain or internally to an other user on the same instance. Returns the payment details.
 */
export const walletPay = <ThrowOnError extends boolean = false>(
  options: Options<WalletPayData, ThrowOnError>
): RequestResult<WalletPayResponses, WalletPayErrors, ThrowOnError> =>
  (options.client ?? client).post<WalletPayResponses, WalletPayErrors, ThrowOnError>({
    responseTransformer: walletPayResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/payments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Find a payment
 *
 * Returns the payment by its ID
 */
export const getWalletPayment = <ThrowOnError extends boolean = false>(
  options: Options<GetWalletPaymentData, ThrowOnError>
): RequestResult<GetWalletPaymentResponses, GetWalletPaymentErrors, ThrowOnError> =>
  (options.client ?? client).get<GetWalletPaymentResponses, GetWalletPaymentErrors, ThrowOnError>({
    responseTransformer: getWalletPaymentResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me/payments/{id}',
    ...options,
  });

/**
 * Delete payments
 *
 * Deletes all the payments given a filter. Returns the number of deleted payments. Deleting a payment can have an effect on the user balance
 */
export const deletePayments = <ThrowOnError extends boolean = false>(
  options?: Options<DeletePaymentsData, ThrowOnError>
): RequestResult<DeletePaymentsResponses, DeletePaymentsErrors, ThrowOnError> =>
  (options?.client ?? client).delete<DeletePaymentsResponses, DeletePaymentsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/payments',
    ...options,
  });

/**
 * List payments
 *
 * Returns all the payments given a filter
 */
export const listPayments = <ThrowOnError extends boolean = false>(
  options?: Options<ListPaymentsData, ThrowOnError>
): RequestResult<ListPaymentsResponses, ListPaymentsErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListPaymentsResponses, ListPaymentsErrors, ThrowOnError>({
    responseTransformer: listPaymentsResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/payments',
    ...options,
  });

/**
 * Send a payment
 *
 * Pay for a LN invoice, LNURL, LN Address, On-chain or internally to an other user on the same instance. Returns the payment details.
 */
export const pay = <ThrowOnError extends boolean = false>(
  options: Options<PayData, ThrowOnError>
): RequestResult<PayResponses, PayErrors, ThrowOnError> =>
  (options.client ?? client).post<PayResponses, PayErrors, ThrowOnError>({
    responseTransformer: payResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/payments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a payment
 *
 * Deletes a payment by ID. Returns an empty body. Deleting a payment has an effect on the user balance
 */
export const deletePayment = <ThrowOnError extends boolean = false>(
  options: Options<DeletePaymentData, ThrowOnError>
): RequestResult<DeletePaymentResponses, DeletePaymentErrors, ThrowOnError> =>
  (options.client ?? client).delete<DeletePaymentResponses, DeletePaymentErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/payments/{id}',
    ...options,
  });

/**
 * Find a payment
 *
 * Returns the payment by its ID.
 */
export const getPayment = <ThrowOnError extends boolean = false>(
  options: Options<GetPaymentData, ThrowOnError>
): RequestResult<GetPaymentResponses, GetPaymentErrors, ThrowOnError> =>
  (options.client ?? client).get<GetPaymentResponses, GetPaymentErrors, ThrowOnError>({
    responseTransformer: getPaymentResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/payments/{id}',
    ...options,
  });

/**
 * Health Check
 *
 * Returns the health of the system fine-grained by dependency.
 */
export const healthCheck = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckData, ThrowOnError>
): RequestResult<HealthCheckResponses, HealthCheckErrors, ThrowOnError> =>
  (options?.client ?? client).get<HealthCheckResponses, HealthCheckErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/system/health',
    ...options,
  });

/**
 * Marks the welcome flow as completed
 *
 * Returns whether the application welcome flow is complete.
 */
export const markWelcomeComplete = <ThrowOnError extends boolean = false>(
  options?: Options<MarkWelcomeCompleteData, ThrowOnError>
): RequestResult<MarkWelcomeCompleteResponses, MarkWelcomeCompleteErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    MarkWelcomeCompleteResponses,
    MarkWelcomeCompleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/system/mark-welcome-complete',
    ...options,
  });

/**
 * Readiness Check
 *
 * Returns successfully if the server is reachable.
 */
export const readinessCheck = <ThrowOnError extends boolean = false>(
  options?: Options<ReadinessCheckData, ThrowOnError>
): RequestResult<ReadinessCheckResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ReadinessCheckResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/system/ready',
    ...options,
  });

/**
 * Setup Status Check
 *
 * Returns whether the application setup is complete.
 */
export const setupCheck = <ThrowOnError extends boolean = false>(
  options?: Options<SetupCheckData, ThrowOnError>
): RequestResult<SetupCheckResponses, SetupCheckErrors, ThrowOnError> =>
  (options?.client ?? client).get<SetupCheckResponses, SetupCheckErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/system/setup',
    ...options,
  });

/**
 * Version Information
 *
 * Returns the current version and build time of the system.
 */
export const versionCheck = <ThrowOnError extends boolean = false>(
  options?: Options<VersionCheckData, ThrowOnError>
): RequestResult<VersionCheckResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<VersionCheckResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/system/version',
    ...options,
  });

/**
 * Delete wallets
 *
 * Deletes all the wallets given a filter. Returns the number of deleted wallets. Deleting a wallet removes all data related to that wallet.
 */
export const deleteWallets = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteWalletsData, ThrowOnError>
): RequestResult<DeleteWalletsResponses, DeleteWalletsErrors, ThrowOnError> =>
  (options?.client ?? client).delete<DeleteWalletsResponses, DeleteWalletsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/wallets',
    ...options,
  });

/**
 * List wallets
 *
 * Returns all the wallets without any linked data. Use the wallet ID to get the full wallet details.
 */
export const listWallets = <ThrowOnError extends boolean = false>(
  options?: Options<ListWalletsData, ThrowOnError>
): RequestResult<ListWalletsResponses, ListWalletsErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListWalletsResponses, ListWalletsErrors, ThrowOnError>({
    responseTransformer: listWalletsResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/wallets',
    ...options,
  });

/**
 * Register a new wallet
 *
 * Returns the generated wallet for the given user
 */
export const registerWallet = <ThrowOnError extends boolean = false>(
  options: Options<RegisterWalletData, ThrowOnError>
): RequestResult<RegisterWalletResponses, RegisterWalletErrors, ThrowOnError> =>
  (options.client ?? client).post<RegisterWalletResponses, RegisterWalletErrors, ThrowOnError>({
    responseTransformer: registerWalletResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/wallets',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List wallet overviews
 *
 * Returns all the wallet overviews. A wallet overview is a summary of a wallet with the number of payments, invoices and contacts.
 */
export const listWalletOverviews = <ThrowOnError extends boolean = false>(
  options?: Options<ListWalletOverviewsData, ThrowOnError>
): RequestResult<ListWalletOverviewsResponses, ListWalletOverviewsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListWalletOverviewsResponses,
    ListWalletOverviewsErrors,
    ThrowOnError
  >({
    responseTransformer: listWalletOverviewsResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/wallets/overviews',
    ...options,
  });

/**
 * Delete a wallet
 *
 * Deletes an wallet by ID. Returns an empty body. Deleting a wallet removes all data related to that wallet.
 */
export const deleteWallet = <ThrowOnError extends boolean = false>(
  options: Options<DeleteWalletData, ThrowOnError>
): RequestResult<DeleteWalletResponses, DeleteWalletErrors, ThrowOnError> =>
  (options.client ?? client).delete<DeleteWalletResponses, DeleteWalletErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/wallets/{id}',
    ...options,
  });

/**
 * Find a wallet
 *
 * Returns the wallet by its ID.
 */
export const getWallet = <ThrowOnError extends boolean = false>(
  options: Options<GetWalletData, ThrowOnError>
): RequestResult<GetWalletResponses, GetWalletErrors, ThrowOnError> =>
  (options.client ?? client).get<GetWalletResponses, GetWalletErrors, ThrowOnError>({
    responseTransformer: getWalletResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/wallets/{id}',
    ...options,
  });
