// This file is auto-generated by @hey-api/openapi-ts

import type {
  CreateAccountApiKeyResponse,
  CreateAccountResponse,
  CreateAccountWalletResponse,
  CreateApiKeyResponse,
  GenerateBtcAddressResponse,
  GenerateInvoiceResponse,
  GetAccountAddressResponse,
  GetAccountApiKeyResponse,
  GetAccountByIdResponse,
  GetAccountPreferencesResponse,
  GetAccountResponse,
  GetAccountWalletResponse,
  GetAddressResponse,
  GetApiKeyResponse,
  GetBtcAddressResponse,
  GetInvoiceResponse,
  GetPaymentResponse,
  GetWalletInvoiceResponse,
  GetWalletPaymentResponse,
  GetWalletResponse,
  ListAccountApiKeysResponse,
  ListAccountsResponse,
  ListAccountWalletsResponse,
  ListAddressesResponse,
  ListApiKeysResponse,
  ListBtcAddressesResponse,
  ListContactsResponse,
  ListInvoicesResponse,
  ListPaymentsResponse,
  ListWalletBtcAddressesResponse,
  ListWalletInvoicesResponse,
  ListWalletOverviewsResponse,
  ListWalletPaymentsResponse,
  ListWalletsResponse,
  NewWalletBtcAddressResponse,
  NewWalletInvoiceResponse,
  PayResponse,
  RegisterAccountAddressResponse,
  RegisterAddressResponse,
  RegisterWalletResponse,
  ReplaceAccountPermissionsResponse,
  UpdateAccountAddressResponse,
  UpdateAccountByIdResponse,
  UpdateAccountPreferencesResponse,
  UpdateAddressResponse,
  UpdateCurrentAccountResponse,
  WalletPayResponse,
} from './types.gen';

const authIdentitySchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

const accountPreferencesSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.updated_at) {
    data.updated_at = new Date(data.updated_at);
  }
  return data;
};

const accountSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.identity) {
    data.identity = authIdentitySchemaResponseTransformer(data.identity);
  }
  if (data.preferences) {
    data.preferences = accountPreferencesSchemaResponseTransformer(data.preferences);
  }
  if (data.updated_at) {
    data.updated_at = new Date(data.updated_at);
  }
  return data;
};

export const listAccountsResponseTransformer = async (data: any): Promise<ListAccountsResponse> => {
  data = data.map((item: any) => accountSchemaResponseTransformer(item));
  return data;
};

export const createAccountResponseTransformer = async (
  data: any
): Promise<CreateAccountResponse> => {
  data = accountSchemaResponseTransformer(data);
  return data;
};

export const getAccountByIdResponseTransformer = async (
  data: any
): Promise<GetAccountByIdResponse> => {
  data = accountSchemaResponseTransformer(data);
  return data;
};

export const updateAccountByIdResponseTransformer = async (
  data: any
): Promise<UpdateAccountByIdResponse> => {
  data = accountSchemaResponseTransformer(data);
  return data;
};

export const replaceAccountPermissionsResponseTransformer = async (
  data: any
): Promise<ReplaceAccountPermissionsResponse> => {
  data = accountSchemaResponseTransformer(data);
  return data;
};

const apiKeySchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.expires_at) {
    data.expires_at = new Date(data.expires_at);
  }
  return data;
};

export const listApiKeysResponseTransformer = async (data: any): Promise<ListApiKeysResponse> => {
  data = data.map((item: any) => apiKeySchemaResponseTransformer(item));
  return data;
};

export const createApiKeyResponseTransformer = async (data: any): Promise<CreateApiKeyResponse> => {
  data = apiKeySchemaResponseTransformer(data);
  return data;
};

export const getApiKeyResponseTransformer = async (data: any): Promise<GetApiKeyResponse> => {
  data = apiKeySchemaResponseTransformer(data);
  return data;
};

const btcAddressSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.updated_at) {
    data.updated_at = new Date(data.updated_at);
  }
  return data;
};

export const listBtcAddressesResponseTransformer = async (
  data: any
): Promise<ListBtcAddressesResponse> => {
  data = data.map((item: any) => btcAddressSchemaResponseTransformer(item));
  return data;
};

export const generateBtcAddressResponseTransformer = async (
  data: any
): Promise<GenerateBtcAddressResponse> => {
  data = btcAddressSchemaResponseTransformer(data);
  return data;
};

export const getBtcAddressResponseTransformer = async (
  data: any
): Promise<GetBtcAddressResponse> => {
  data = btcAddressSchemaResponseTransformer(data);
  return data;
};

const btcOutputSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.updated_at) {
    data.updated_at = new Date(data.updated_at);
  }
  return data;
};

const lnInvoiceSchemaResponseTransformer = (data: any) => {
  data.expires_at = new Date(data.expires_at);
  return data;
};

const invoiceSchemaResponseTransformer = (data: any) => {
  if (data.bitcoin_output) {
    data.bitcoin_output = btcOutputSchemaResponseTransformer(data.bitcoin_output);
  }
  data.created_at = new Date(data.created_at);
  if (data.ln_invoice) {
    data.ln_invoice = lnInvoiceSchemaResponseTransformer(data.ln_invoice);
  }
  if (data.payment_time) {
    data.payment_time = new Date(data.payment_time);
  }
  data.timestamp = new Date(data.timestamp);
  if (data.updated_at) {
    data.updated_at = new Date(data.updated_at);
  }
  return data;
};

export const listInvoicesResponseTransformer = async (data: any): Promise<ListInvoicesResponse> => {
  data = data.map((item: any) => invoiceSchemaResponseTransformer(item));
  return data;
};

export const generateInvoiceResponseTransformer = async (
  data: any
): Promise<GenerateInvoiceResponse> => {
  data = invoiceSchemaResponseTransformer(data);
  return data;
};

export const getInvoiceResponseTransformer = async (data: any): Promise<GetInvoiceResponse> => {
  data = invoiceSchemaResponseTransformer(data);
  return data;
};

const lnAddressSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.updated_at) {
    data.updated_at = new Date(data.updated_at);
  }
  return data;
};

export const listAddressesResponseTransformer = async (
  data: any
): Promise<ListAddressesResponse> => {
  data = data.map((item: any) => lnAddressSchemaResponseTransformer(item));
  return data;
};

export const registerAddressResponseTransformer = async (
  data: any
): Promise<RegisterAddressResponse> => {
  data = lnAddressSchemaResponseTransformer(data);
  return data;
};

export const getAddressResponseTransformer = async (data: any): Promise<GetAddressResponse> => {
  data = lnAddressSchemaResponseTransformer(data);
  return data;
};

export const updateAddressResponseTransformer = async (
  data: any
): Promise<UpdateAddressResponse> => {
  data = lnAddressSchemaResponseTransformer(data);
  return data;
};

export const getAccountResponseTransformer = async (data: any): Promise<GetAccountResponse> => {
  data = accountSchemaResponseTransformer(data);
  return data;
};

export const updateCurrentAccountResponseTransformer = async (
  data: any
): Promise<UpdateCurrentAccountResponse> => {
  data = accountSchemaResponseTransformer(data);
  return data;
};

export const listAccountApiKeysResponseTransformer = async (
  data: any
): Promise<ListAccountApiKeysResponse> => {
  data = data.map((item: any) => apiKeySchemaResponseTransformer(item));
  return data;
};

export const createAccountApiKeyResponseTransformer = async (
  data: any
): Promise<CreateAccountApiKeyResponse> => {
  data = apiKeySchemaResponseTransformer(data);
  return data;
};

export const getAccountApiKeyResponseTransformer = async (
  data: any
): Promise<GetAccountApiKeyResponse> => {
  data = apiKeySchemaResponseTransformer(data);
  return data;
};

export const getAccountAddressResponseTransformer = async (
  data: any
): Promise<GetAccountAddressResponse> => {
  if (data) {
    data = lnAddressSchemaResponseTransformer(data);
  }
  return data;
};

export const registerAccountAddressResponseTransformer = async (
  data: any
): Promise<RegisterAccountAddressResponse> => {
  data = lnAddressSchemaResponseTransformer(data);
  return data;
};

export const updateAccountAddressResponseTransformer = async (
  data: any
): Promise<UpdateAccountAddressResponse> => {
  data = lnAddressSchemaResponseTransformer(data);
  return data;
};

export const getAccountPreferencesResponseTransformer = async (
  data: any
): Promise<GetAccountPreferencesResponse> => {
  data = accountPreferencesSchemaResponseTransformer(data);
  return data;
};

export const updateAccountPreferencesResponseTransformer = async (
  data: any
): Promise<UpdateAccountPreferencesResponse> => {
  data = accountPreferencesSchemaResponseTransformer(data);
  return data;
};

const assetSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.updated_at) {
    data.updated_at = new Date(data.updated_at);
  }
  return data;
};

const contactSchemaResponseTransformer = (data: any) => {
  data.contact_since = new Date(data.contact_since);
  return data;
};

const paymentSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.payment_time) {
    data.payment_time = new Date(data.payment_time);
  }
  if (data.updated_at) {
    data.updated_at = new Date(data.updated_at);
  }
  return data;
};

const walletSchemaResponseTransformer = (data: any) => {
  if (data.asset) {
    data.asset = assetSchemaResponseTransformer(data.asset);
  }
  data.btc_addresses = data.btc_addresses.map((item: any) =>
    btcAddressSchemaResponseTransformer(item)
  );
  data.contacts = data.contacts.map((item: any) => contactSchemaResponseTransformer(item));
  data.created_at = new Date(data.created_at);
  data.invoices = data.invoices.map((item: any) => invoiceSchemaResponseTransformer(item));
  if (data.ln_address) {
    data.ln_address = lnAddressSchemaResponseTransformer(data.ln_address);
  }
  data.payments = data.payments.map((item: any) => paymentSchemaResponseTransformer(item));
  if (data.updated_at) {
    data.updated_at = new Date(data.updated_at);
  }
  return data;
};

export const listAccountWalletsResponseTransformer = async (
  data: any
): Promise<ListAccountWalletsResponse> => {
  data = data.map((item: any) => walletSchemaResponseTransformer(item));
  return data;
};

export const createAccountWalletResponseTransformer = async (
  data: any
): Promise<CreateAccountWalletResponse> => {
  data = walletSchemaResponseTransformer(data);
  return data;
};

export const getAccountWalletResponseTransformer = async (
  data: any
): Promise<GetAccountWalletResponse> => {
  data = walletSchemaResponseTransformer(data);
  return data;
};

export const listWalletBtcAddressesResponseTransformer = async (
  data: any
): Promise<ListWalletBtcAddressesResponse> => {
  data = data.map((item: any) => btcAddressSchemaResponseTransformer(item));
  return data;
};

export const newWalletBtcAddressResponseTransformer = async (
  data: any
): Promise<NewWalletBtcAddressResponse> => {
  data = btcAddressSchemaResponseTransformer(data);
  return data;
};

export const listContactsResponseTransformer = async (data: any): Promise<ListContactsResponse> => {
  data = data.map((item: any) => contactSchemaResponseTransformer(item));
  return data;
};

export const listWalletInvoicesResponseTransformer = async (
  data: any
): Promise<ListWalletInvoicesResponse> => {
  data = data.map((item: any) => invoiceSchemaResponseTransformer(item));
  return data;
};

export const newWalletInvoiceResponseTransformer = async (
  data: any
): Promise<NewWalletInvoiceResponse> => {
  data = invoiceSchemaResponseTransformer(data);
  return data;
};

export const getWalletInvoiceResponseTransformer = async (
  data: any
): Promise<GetWalletInvoiceResponse> => {
  data = invoiceSchemaResponseTransformer(data);
  return data;
};

export const listWalletPaymentsResponseTransformer = async (
  data: any
): Promise<ListWalletPaymentsResponse> => {
  data = data.map((item: any) => paymentSchemaResponseTransformer(item));
  return data;
};

export const walletPayResponseTransformer = async (data: any): Promise<WalletPayResponse> => {
  data = paymentSchemaResponseTransformer(data);
  return data;
};

export const getWalletPaymentResponseTransformer = async (
  data: any
): Promise<GetWalletPaymentResponse> => {
  data = paymentSchemaResponseTransformer(data);
  return data;
};

export const listPaymentsResponseTransformer = async (data: any): Promise<ListPaymentsResponse> => {
  data = data.map((item: any) => paymentSchemaResponseTransformer(item));
  return data;
};

export const payResponseTransformer = async (data: any): Promise<PayResponse> => {
  data = paymentSchemaResponseTransformer(data);
  return data;
};

export const getPaymentResponseTransformer = async (data: any): Promise<GetPaymentResponse> => {
  data = paymentSchemaResponseTransformer(data);
  return data;
};

export const listWalletsResponseTransformer = async (data: any): Promise<ListWalletsResponse> => {
  data = data.map((item: any) => walletSchemaResponseTransformer(item));
  return data;
};

export const registerWalletResponseTransformer = async (
  data: any
): Promise<RegisterWalletResponse> => {
  data = walletSchemaResponseTransformer(data);
  return data;
};

const walletOverviewSchemaResponseTransformer = (data: any) => {
  if (data.asset) {
    data.asset = assetSchemaResponseTransformer(data.asset);
  }
  data.created_at = new Date(data.created_at);
  if (data.ln_address) {
    data.ln_address = lnAddressSchemaResponseTransformer(data.ln_address);
  }
  if (data.updated_at) {
    data.updated_at = new Date(data.updated_at);
  }
  return data;
};

export const listWalletOverviewsResponseTransformer = async (
  data: any
): Promise<ListWalletOverviewsResponse> => {
  data = data.map((item: any) => walletOverviewSchemaResponseTransformer(item));
  return data;
};

export const getWalletResponseTransformer = async (data: any): Promise<GetWalletResponse> => {
  data = walletSchemaResponseTransformer(data);
  return data;
};
