// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://src` | (string & {});
};

/**
 * API Key
 */
export type ApiKey = {
  /**
   * Owning account ID
   */
  account_id: string;
  /**
   * Date of creation in database
   */
  created_at: Date;
  /**
   * API key description
   */
  description?: string | null;
  /**
   * Date of expiration
   */
  expires_at?: Date | null;
  /**
   * Internal ID
   */
  id: string;
  /**
   * API key (only returned once on creation, save it securely as it cannot be retrieved)
   */
  key?: string | null;
  /**
   * API key name
   */
  name: string;
  /**
   * List of permissions for this API key
   */
  permissions: Array<Permission>;
  /**
   * Auth provider subject this key authenticates as.
   *
   * Ownership is enforced through `account_id`; this subject is the
   * request-time actor label returned by authentication.
   */
  user_id: string;
};

/**
 * A spendable asset on one protocol/network.
 */
export type Asset = {
  /**
   * Protocol-specific asset reference; native for chain-native BTC
   */
  asset_ref: string;
  /**
   * Stable server asset code, independent of network-specific UI ticker.
   */
  code: string;
  /**
   * Date of creation in database
   */
  created_at: Date;
  /**
   * Integer storage scale for this asset
   */
  decimals: number;
  /**
   * UI ticker for the specific network, such as BTC, tBTC, or rBTC.
   */
  display_ticker: string;
  /**
   * Internal asset ID
   */
  id: string;
  /**
   * Optional display name
   */
  name?: string | null;
  /**
   * Settlement network, such as bitcoin/mainnet or bitcoin/regtest
   */
  network: string;
  /**
   * Settlement protocol, such as bitcoin or taproot_assets
   */
  protocol: string;
  /**
   * Date of update in database
   */
  updated_at?: Date | null;
};

/**
 * A wallet's balance, in millisatoshis.
 */
export type Balance = {
  /**
   * Amount available to spend.
   */
  available_msat: number;
  /**
   * Total fees paid
   */
  fees_paid_msat: number;
  /**
   * Total amount received
   */
  received_msat: number;
  /**
   * Amount reserved for pending outgoing payments
   */
  reserved_msat: number;
  /**
   * Total amount sent (settled outgoing payments)
   */
  sent_msat: number;
};

/**
 * Bitcoin Address
 */
export type BtcAddress = {
  /**
   * Current deposit address
   */
  address: string;
  /**
   * Address type
   */
  address_type: BtcAddressType;
  /**
   * Date of creation in database
   */
  created_at: Date;
  /**
   * Internal ID
   */
  id: string;
  /**
   * Date of update in database
   */
  updated_at?: Date | null;
  /**
   * Whether the address has already been used on-chain
   */
  used: boolean;
  /**
   * Wallet ID
   */
  wallet_id: string;
};

/**
 * Bitcoin address script type.
 */
export const BtcAddressType = {
  P2PKH: 'p2pkh',
  P2SH: 'p2sh',
  P2WPKH: 'p2wpkh',
  P2TR: 'p2tr',
} as const;

/**
 * Bitcoin address script type.
 */
export type BtcAddressType = (typeof BtcAddressType)[keyof typeof BtcAddressType];

/**
 * A Bitcoin network.
 */
export const BtcNetwork = {
  BITCOIN: 'Bitcoin',
  TESTNET: 'Testnet',
  TESTNET4: 'Testnet4',
  REGTEST: 'Regtest',
  SIMNET: 'Simnet',
  SIGNET: 'Signet',
} as const;

/**
 * A Bitcoin network.
 */
export type BtcNetwork = (typeof BtcNetwork)[keyof typeof BtcNetwork];

/**
 * Bitcoin Output
 */
export type BtcOutput = {
  /**
   * Address
   */
  address: string;
  /**
   * Amount in satoshis
   */
  amount_sat: number;
  /**
   * Block height
   */
  block_height?: number | null;
  /**
   * Date of creation in database
   */
  created_at: Date;
  /**
   * Internal ID
   */
  id: string;
  /**
   * Outpoint
   */
  outpoint: string;
  /**
   * Status
   */
  status: BtcOutputStatus;
  /**
   * Date of update in database
   */
  updated_at?: Date | null;
};

/**
 * Confirmation status of an on-chain output.
 */
export const BtcOutputStatus = {
  UNCONFIRMED: 'Unconfirmed',
  CONFIRMED: 'Confirmed',
  SPENT: 'Spent',
  IMMATURE: 'Immature',
} as const;

/**
 * Confirmation status of an on-chain output.
 */
export type BtcOutputStatus = (typeof BtcOutputStatus)[keyof typeof BtcOutputStatus];

/**
 * On-chain Bitcoin details of a payment.
 */
export type BtcPayment = {
  /**
   * Destination Bitcoin address. Populated for Bitcoin onchain payments.
   */
  address: string;
  /**
   * Bitcoin block height where the transaction was confirmed.
   */
  block_height?: number | null;
  /**
   * Transaction ID for on-chain payments.
   */
  txid: string;
};

/**
 * Change Password Request
 */
export type ChangePasswordRequest = {
  /**
   * Current user password
   */
  current_password: string;
  /**
   * New user password
   */
  new_password: string;
};

/**
 * A counterparty the wallet has paid, with the date of first contact.
 */
export type Contact = {
  /**
   * Date of first payment to this contact
   */
  contact_since: Date;
  /**
   * Lightning Address
   */
  ln_address: string;
};

/**
 * Create API Key Request
 */
export type CreateApiKeyRequest = {
  /**
   * API key description
   */
  description?: string | null;
  /**
   * Expiration time in seconds
   */
  expiry?: number | null;
  /**
   * API key name
   */
  name: string;
  /**
   * List of permissions for this API key
   */
  permissions: Array<Permission>;
  /**
   * Auth provider subject to mint the key for.
   *
   * User-scoped endpoints populate this with your own subject.
   */
  user_id?: string | null;
};

/**
 * Create Wallet Request
 */
export type CreateWalletRequest = {
  /**
   * Owning account ID
   */
  account_id: string;
  /**
   * Asset ID to enable for the account
   */
  asset_id: string;
};

/**
 * The currency and network a transaction is denominated in.
 */
export const Currency = {
  BITCOIN: 'Bitcoin',
  BITCOIN_TESTNET: 'BitcoinTestnet',
  REGTEST: 'Regtest',
  SIMNET: 'Simnet',
  SIGNET: 'Signet',
} as const;

/**
 * The currency and network a transaction is denominated in.
 */
export type Currency = (typeof Currency)[keyof typeof Currency];

/**
 * Application error response
 */
export type ErrorResponse = {
  /**
   * Error reason
   */
  reason: string;
  /**
   * Error status
   */
  status: string;
};

/**
 * App health information, fine-grained by dependency.
 */
export type HealthCheck = {
  /**
   * Health of the database
   */
  database: HealthStatus;
  /**
   * Whether the system is healthy and can be used
   */
  is_healthy: boolean;
  /**
   * Health of the Lightning provider service
   */
  ln_provider: HealthStatus;
};

/**
 * Health of a single system dependency.
 */
export const HealthStatus = {
  OPERATIONAL: 'Operational',
  UNAVAILABLE: 'Unavailable',
  MAINTENANCE: 'Maintenance',
} as const;

/**
 * Health of a single system dependency.
 */
export type HealthStatus = (typeof HealthStatus)[keyof typeof HealthStatus];

/**
 * Details of a payment settled internally between wallets on the same instance.
 */
export type InternalPayment = {
  /**
   * Bitcoin Address. Populated for internal Bitcoin address payments
   */
  btc_address?: string | null;
  /**
   * Lightning Address. Populated for internal LN Address payments
   */
  ln_address?: string | null;
  /**
   * Payment hash. Populated for internal bolt11 payments
   */
  payment_hash?: string | null;
};

/**
 * An incoming payment request, over Lightning and/or on-chain.
 */
export type Invoice = {
  /**
   * Amount requested in millisatoshis.
   */
  amount_msat?: number | null;
  /**
   * Amount received in millisatoshis.
   */
  amount_received_msat?: number | null;
  bitcoin_output?: null | BtcOutput;
  /**
   * Date of creation in database
   */
  created_at: Date;
  /**
   * Currency
   */
  currency: Currency;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Fees paid. Populated when a new channel is opened to receive the funds.
   */
  fee_msat?: number | null;
  /**
   * Internal ID
   */
  id: string;
  /**
   * Ledger
   */
  ledger: Ledger;
  /**
   * Lightning Address. Populated when invoice is generated as part of the LNURL protocol
   */
  ln_address_id?: string | null;
  ln_invoice?: null | LnInvoice;
  /**
   * Payment time
   */
  payment_time?: Date | null;
  /**
   * Status
   */
  status: InvoiceStatus;
  /**
   * Date of creation on the LN node
   */
  timestamp: Date;
  /**
   * Date of update in database
   */
  updated_at?: Date | null;
  /**
   * Wallet ID
   */
  wallet_id: string;
};

/**
 * Field to order invoices by.
 */
export const InvoiceOrderBy = {
  CREATED_AT: 'CreatedAt',
  PAYMENT_TIME: 'PaymentTime',
  UPDATED_AT: 'UpdatedAt',
} as const;

/**
 * Field to order invoices by.
 */
export type InvoiceOrderBy = (typeof InvoiceOrderBy)[keyof typeof InvoiceOrderBy];

/**
 * Lifecycle status of an invoice.
 */
export const InvoiceStatus = {
  PENDING: 'Pending',
  SETTLED: 'Settled',
  EXPIRED: 'Expired',
} as const;

/**
 * Lifecycle status of an invoice.
 */
export type InvoiceStatus = (typeof InvoiceStatus)[keyof typeof InvoiceStatus];

/**
 * The ledger a transaction settles on.
 */
export const Ledger = {
  LIGHTNING: 'Lightning',
  INTERNAL: 'Internal',
  ONCHAIN: 'Onchain',
} as const;

/**
 * The ledger a transaction settles on.
 */
export type Ledger = (typeof Ledger)[keyof typeof Ledger];

/**
 * Lightning Address
 */
export type LnAddress = {
  /**
   * Active status. Inactive addresses cannot receive funds
   */
  active: boolean;
  /**
   * Nostr enabled
   */
  allows_nostr: boolean;
  /**
   * Date of creation in database
   */
  created_at: Date;
  /**
   * Internal ID
   */
  id: string;
  /**
   * Nostr Public key
   */
  nostr_pubkey?: string | null;
  /**
   * Date of update in database
   */
  updated_at?: Date | null;
  /**
   * Username
   */
  username: string;
  /**
   * Wallet ID
   */
  wallet_id: string;
};

/**
 * Lightning-specific details of an invoice.
 */
export type LnInvoice = {
  /**
   * Bolt11
   */
  bolt11: string;
  /**
   * Description hash
   */
  description_hash?: string | null;
  /**
   * Date of expiry
   */
  expires_at: Date;
  /**
   * Duration of expiry in seconds since creation
   */
  expiry: number;
  /**
   * The minimum number of blocks the final hop in the route should wait before allowing the payment to be claimed. This is a security measure to ensure that the payment can be settled properly
   */
  min_final_cltv_expiry_delta: number;
  /**
   * Public key of the node receiving the funds
   */
  payee_pubkey: string;
  /**
   * Payment hash
   */
  payment_hash: string;
  /**
   * A secret value included in the payment request to mitigate certain types of attacks. The payment secret must be provided by the payer when making the payment
   */
  payment_secret: string;
};

/**
 * Lightning-specific details of a payment.
 */
export type LnPayment = {
  /**
   * Lightning Address. Populated when sending to a LN Address
   */
  ln_address?: string | null;
  /**
   * Metadata
   */
  metadata?: string | null;
  /**
   * Payment hash
   */
  payment_hash: string;
  /**
   * Payment Preimage
   */
  payment_preimage?: string | null;
  success_action?: null | LnUrlSuccessAction;
};

/**
 * LNURL-pay `payRequest` response served at the well-known endpoint (LUD-06).
 */
export type LnUrlPayRequest = {
  /**
   * Nostr enabled
   */
  allowsNostr: boolean;
  /**
   * The URL from LN SERVICE to accept the pay request
   */
  callback: string;
  /**
   * Optional number of characters accepted for the `comment` query parameter on subsequent callback, defaults to 0 if not provided. (no comment allowed). See <https://github.com/lnurl/luds/blob/luds/12.md>
   */
  commentAllowed: number;
  /**
   * Max amount in milli-satoshis LN SERVICE is willing to receive
   */
  maxSendable: number;
  /**
   * Metadata json which must be presented as raw string here, this is required to pass signature verification at a later step
   */
  metadata: string;
  /**
   * Min amount in milli-satoshis LN SERVICE is willing to receive, can not be less than 1 or more than `maxSendable`
   */
  minSendable: number;
  /**
   * Nostr public key
   */
  nostrPubkey?: string | null;
  /**
   * Type of LNURL
   */
  tag: string;
};

/**
 * LNURL-pay callback response. Carries the invoice to pay and how to behave on
 * success. Wire shape follows LUD-06 (camelCase fields).
 */
export type LnUrlCallback = {
  /**
   * An optional flag to let a wallet know whether to persist the link from step 1, if null should be interpreted as true
   */
  disposable?: boolean | null;
  /**
   * bech32-serialized Lightning invoice
   */
  pr: string;
  /**
   * array with payment routes, should be left empty if no routes are to be provided
   */
  routes: Array<string>;
  successAction?: null | LnUrlSuccessAction;
};

/**
 * LNURL success action shown to the payer after a successful payment (LUD-09).
 */
export type LnUrlSuccessAction = {
  /**
   * Description
   */
  description?: string | null;
  /**
   * Message displayed to the user
   */
  message?: string | null;
  /**
   * Action type. One of `url` or `message`
   */
  tag: string;
  /**
   * URL for the user to open on success
   */
  url?: string | null;
};

/**
 * New Bitcoin Address Request
 */
export type NewBtcAddressRequest = {
  type?: null | BtcAddressType;
  /**
   * User ID. Will be populated with your own ID by default
   */
  wallet_id?: string | null;
};

/**
 * New Invoice Request
 */
export type NewInvoiceRequest = {
  /**
   * Amount in millisatoshis
   */
  amount_msat: number;
  /**
   * Description of the invoice. Visible by the payer
   */
  description?: string | null;
  /**
   * Expiration time in seconds
   */
  expiry?: number | null;
  /**
   * User ID. Will be populated with your own ID by default
   */
  wallet_id?: string | null;
};

/**
 * Nostr NIP-05 response. Maps each queried name to its hex-encoded public key.
 */
export type NostrNip05Response = {
  /**
   * Found names, keyed by username and valued by hex-encoded public key
   */
  names: {
    [key: string]: string;
  };
};

/**
 * Direction of result ordering for list endpoints.
 */
export const OrderDirection = { ASC: 'Asc', DESC: 'Desc' } as const;

/**
 * Direction of result ordering for list endpoints.
 */
export type OrderDirection = (typeof OrderDirection)[keyof typeof OrderDirection];

/**
 * An outgoing payment, over Lightning, on-chain, or internal to the instance.
 */
export type Payment = {
  /**
   * Amount in millisatoshis.
   */
  amount_msat: number;
  bitcoin?: null | BtcPayment;
  /**
   * Date of creation in database
   */
  created_at: Date;
  /**
   * Currency
   */
  currency: Currency;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Error message
   */
  error?: string | null;
  /**
   * Fees paid. Populated when a new channel is opened to receive the funds
   */
  fee_msat?: number | null;
  /**
   * Internal ID
   */
  id: string;
  internal?: null | InternalPayment;
  /**
   * Ledger
   */
  ledger: Ledger;
  lightning?: null | LnPayment;
  /**
   * Payment time
   */
  payment_time?: Date | null;
  /**
   * Status
   */
  status: PaymentStatus;
  /**
   * Date of update in database
   */
  updated_at?: Date | null;
  /**
   * Wallet ID
   */
  wallet_id: string;
};

/**
 * Lifecycle status of a payment.
 */
export const PaymentStatus = {
  PENDING: 'Pending',
  SETTLED: 'Settled',
  FAILED: 'Failed',
} as const;

/**
 * Lifecycle status of a payment.
 */
export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus];

/**
 * An API access scope granted to a JWT or API key.
 */
export const Permission = {
  READ_WALLET: 'read:wallet',
  WRITE_WALLET: 'write:wallet',
  READ_LN_ADDRESS: 'read:ln_address',
  WRITE_LN_ADDRESS: 'write:ln_address',
  READ_TRANSACTION: 'read:transaction',
  WRITE_TRANSACTION: 'write:transaction',
  READ_LN_NODE: 'read:ln_node',
  WRITE_LN_NODE: 'write:ln_node',
  READ_API_KEY: 'read:api_key',
  WRITE_API_KEY: 'write:api_key',
  READ_BTC_ADDRESS: 'read:btc_address',
  WRITE_BTC_ADDRESS: 'write:btc_address',
} as const;

/**
 * An API access scope granted to a JWT or API key.
 */
export type Permission = (typeof Permission)[keyof typeof Permission];

/**
 * Register Lightning Address Request
 */
export type RegisterLnAddressRequest = {
  /**
   * Nostr enabled
   */
  allows_nostr?: boolean;
  /**
   * Nostr public key
   */
  nostr_pubkey?: string | null;
  /**
   * Username such as `username@domain`
   */
  username: string;
  /**
   * Wallet ID. Will be populated with your own ID by default
   */
  wallet_id?: string | null;
};

/**
 * Send Payment Request
 */
export type SendPaymentRequest = {
  /**
   * Amount in millisatoshis. Only necessary if the input does not specify an amount (empty Bolt11, LNURL or LN Address)
   */
  amount_msat?: number | null;
  /**
   * Comment of the payment. Visible by the recipient for LNURL payments
   */
  comment?: string | null;
  /**
   * Recipient. Can be a Bolt11 invoice, LNURL or LN Address.
   */
  input: string;
  /**
   * Wallet ID. Will be populated with your own ID by default
   */
  wallet_id?: string | null;
};

/**
 * App setup info.
 */
export type SetupInfo = {
  /**
   * Whether the admin user has been created
   */
  sign_up_complete: boolean;
  /**
   * Whether the welcome flow has been completed
   */
  welcome_complete: boolean;
};

/**
 * Sign In Request
 */
export type SignInRequest = {
  /**
   * User password
   */
  password: string;
};

/**
 * Sign In Response
 */
export type SignInResponse = {
  /**
   * JWT token
   */
  token: string;
};

/**
 * Sign Up Request
 */
export type SignUpRequest = {
  /**
   * User password
   */
  password: string;
};

/**
 * Update Lightning Address Request
 */
export type UpdateLnAddressRequest = {
  /**
   * Active status
   */
  active?: boolean | null;
  /**
   * Nostr enabled
   */
  allows_nostr?: boolean | null;
  /**
   * Nostr public key
   */
  nostr_pubkey?: string | null;
  /**
   * Username such as `username@domain`
   */
  username?: string | null;
};

/**
 * App version info.
 */
export type VersionInfo = {
  /**
   * Build time of the software
   */
  build_time: string;
  /**
   * Current version of the software
   */
  version: string;
};

/**
 * A user wallet with its balance and linked payments, invoices, Bitcoin addresses and contacts.
 */
export type Wallet = {
  /**
   * Owning account ID
   */
  account_id: string;
  asset?: null | Asset;
  /**
   * Spendable asset held by this wallet
   */
  asset_id: string;
  /**
   * User Balance
   */
  balance: Balance;
  /**
   * List of Bitcoin addresses
   */
  btc_addresses: Array<BtcAddress>;
  /**
   * List of contacts
   */
  contacts: Array<Contact>;
  /**
   * Date of creation in database
   */
  created_at: Date;
  /**
   * Internal ID
   */
  id: string;
  /**
   * List of Invoices
   */
  invoices: Array<Invoice>;
  /**
   * Optional account-specific display label.
   */
  label?: string | null;
  ln_address?: null | LnAddress;
  /**
   * List of payments
   */
  payments: Array<Payment>;
  /**
   * Date of update in database
   */
  updated_at?: Date | null;
};

/**
 * A lightweight wallet summary with counts in place of the full lists.
 */
export type WalletOverview = {
  /**
   * Owning account ID
   */
  account_id: string;
  asset?: null | Asset;
  /**
   * Spendable asset held by this wallet
   */
  asset_id: string;
  /**
   * User Balance
   */
  balance: Balance;
  /**
   * Date of creation in database
   */
  created_at: Date;
  /**
   * Internal ID
   */
  id: string;
  /**
   * Optional account-specific display label.
   */
  label?: string | null;
  ln_address?: null | LnAddress;
  /**
   * Number of contacts
   */
  n_contacts: number;
  /**
   * Number of invoices
   */
  n_invoices: number;
  /**
   * Number of payments
   */
  n_payments: number;
  /**
   * Date of update in database
   */
  updated_at?: Date | null;
};

export type WellKnownData = {
  body?: never;
  path: {
    username: string;
  };
  query?: never;
  url: '/.well-known/lnurlp/{username}';
};

export type WellKnownErrors = {
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type WellKnownError = WellKnownErrors[keyof WellKnownErrors];

export type WellKnownResponses = {
  /**
   * Found
   */
  200: LnUrlPayRequest;
};

export type WellKnownResponse = WellKnownResponses[keyof WellKnownResponses];

export type WellKnownNostrData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Username to query
     */
    name?: string;
  };
  url: '/.well-known/nostr.json';
};

export type WellKnownNostrErrors = {
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type WellKnownNostrError = WellKnownNostrErrors[keyof WellKnownNostrErrors];

export type WellKnownNostrResponses = {
  /**
   * Found
   */
  200: NostrNip05Response;
};

export type WellKnownNostrResponse = WellKnownNostrResponses[keyof WellKnownNostrResponses];

export type CallbackData = {
  body?: never;
  path: {
    username: string;
  };
  query: {
    /**
     * Amount in millisatoshis
     */
    amount: number;
    /**
     * Optional comment for the recipient
     */
    comment?: string | null;
  };
  url: '/lnurlp/{username}/callback';
};

export type CallbackErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type CallbackError = CallbackErrors[keyof CallbackErrors];

export type CallbackResponses = {
  /**
   * Found
   */
  200: LnUrlCallback;
};

export type CallbackResponse = CallbackResponses[keyof CallbackResponses];

export type RevokeApiKeysData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * Auth provider subject to filter by.
     *
     * User-scoped endpoints populate this with your own subject.
     */
    user_id?: string | null;
    /**
     * Owning account ID.
     */
    account_id?: string | null;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/api-keys';
};

export type RevokeApiKeysErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type RevokeApiKeysError = RevokeApiKeysErrors[keyof RevokeApiKeysErrors];

export type RevokeApiKeysResponses = {
  /**
   * Success
   */
  200: number;
};

export type RevokeApiKeysResponse = RevokeApiKeysResponses[keyof RevokeApiKeysResponses];

export type ListApiKeysData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * Auth provider subject to filter by.
     *
     * User-scoped endpoints populate this with your own subject.
     */
    user_id?: string | null;
    /**
     * Owning account ID.
     */
    account_id?: string | null;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/api-keys';
};

export type ListApiKeysErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type ListApiKeysError = ListApiKeysErrors[keyof ListApiKeysErrors];

export type ListApiKeysResponses = {
  /**
   * Success
   */
  200: Array<ApiKey>;
};

export type ListApiKeysResponse = ListApiKeysResponses[keyof ListApiKeysResponses];

export type CreateApiKeyData = {
  body: CreateApiKeyRequest;
  path?: never;
  query?: never;
  url: '/v1/api-keys';
};

export type CreateApiKeyErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type CreateApiKeyError = CreateApiKeyErrors[keyof CreateApiKeyErrors];

export type CreateApiKeyResponses = {
  /**
   * API Key Created
   */
  200: ApiKey;
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type RevokeApiKeyData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/api-keys/{id}';
};

export type RevokeApiKeyErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type RevokeApiKeyError = RevokeApiKeyErrors[keyof RevokeApiKeyErrors];

export type RevokeApiKeyResponses = {
  /**
   * Revoked
   */
  200: unknown;
};

export type GetApiKeyData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/api-keys/{id}';
};

export type GetApiKeyErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetApiKeyError = GetApiKeyErrors[keyof GetApiKeyErrors];

export type GetApiKeyResponses = {
  /**
   * Found
   */
  200: ApiKey;
};

export type GetApiKeyResponse = GetApiKeyResponses[keyof GetApiKeyResponses];

export type ChangePasswordData = {
  body: ChangePasswordRequest;
  path?: never;
  query?: never;
  url: '/v1/auth/change-password';
};

export type ChangePasswordErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Unsupported
   */
  405: ErrorResponse;
  /**
   * Validation failed
   */
  422: ErrorResponse;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
  /**
   * Password changed
   */
  204: void;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type SignInData = {
  body: SignInRequest;
  path?: never;
  query?: never;
  url: '/v1/auth/sign-in';
};

export type SignInErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Unsupported
   */
  405: ErrorResponse;
};

export type SignInError = SignInErrors[keyof SignInErrors];

export type SignInResponses = {
  /**
   * Token Created
   */
  200: SignInResponse;
};

export type SignInResponse2 = SignInResponses[keyof SignInResponses];

export type SignUpData = {
  body: SignUpRequest;
  path?: never;
  query?: never;
  url: '/v1/auth/sign-up';
};

export type SignUpErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Unsupported
   */
  405: ErrorResponse;
  /**
   * Duplicate
   */
  409: ErrorResponse;
};

export type SignUpError = SignUpErrors[keyof SignUpErrors];

export type SignUpResponses = {
  /**
   * Admin user created
   */
  200: SignInResponse;
};

export type SignUpResponse = SignUpResponses[keyof SignUpResponses];

export type DeleteBtcAddressesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * Wallet ID. Automatically populated with your ID
     */
    wallet_id?: string | null;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Status
     */
    address_type?: null | BtcAddressType;
    /**
     * Whether the address has been used
     */
    used?: boolean | null;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/bitcoin/addresses';
};

export type DeleteBtcAddressesErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteBtcAddressesError = DeleteBtcAddressesErrors[keyof DeleteBtcAddressesErrors];

export type DeleteBtcAddressesResponses = {
  /**
   * Success
   */
  200: number;
};

export type DeleteBtcAddressesResponse =
  DeleteBtcAddressesResponses[keyof DeleteBtcAddressesResponses];

export type ListBtcAddressesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * Wallet ID. Automatically populated with your ID
     */
    wallet_id?: string | null;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Status
     */
    address_type?: null | BtcAddressType;
    /**
     * Whether the address has been used
     */
    used?: boolean | null;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/bitcoin/addresses';
};

export type ListBtcAddressesErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type ListBtcAddressesError = ListBtcAddressesErrors[keyof ListBtcAddressesErrors];

export type ListBtcAddressesResponses = {
  /**
   * Success
   */
  200: Array<BtcAddress>;
};

export type ListBtcAddressesResponse = ListBtcAddressesResponses[keyof ListBtcAddressesResponses];

export type GenerateBtcAddressData = {
  body: NewBtcAddressRequest;
  path?: never;
  query?: never;
  url: '/v1/bitcoin/addresses';
};

export type GenerateBtcAddressErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GenerateBtcAddressError = GenerateBtcAddressErrors[keyof GenerateBtcAddressErrors];

export type GenerateBtcAddressResponses = {
  /**
   * Bitcoin Address Created
   */
  200: BtcAddress;
};

export type GenerateBtcAddressResponse =
  GenerateBtcAddressResponses[keyof GenerateBtcAddressResponses];

export type DeleteBtcAddressData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/bitcoin/addresses/{id}';
};

export type DeleteBtcAddressErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteBtcAddressError = DeleteBtcAddressErrors[keyof DeleteBtcAddressErrors];

export type DeleteBtcAddressResponses = {
  /**
   * Deleted
   */
  200: unknown;
};

export type GetBtcAddressData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/bitcoin/addresses/{id}';
};

export type GetBtcAddressErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetBtcAddressError = GetBtcAddressErrors[keyof GetBtcAddressErrors];

export type GetBtcAddressResponses = {
  /**
   * Found
   */
  200: BtcAddress;
};

export type GetBtcAddressResponse = GetBtcAddressResponses[keyof GetBtcAddressResponses];

export type DeleteInvoicesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * Wallet ID. Automatically populated with your ID
     */
    wallet_id?: string | null;
    /**
     * Status
     */
    status?: null | InvoiceStatus;
    /**
     * Ledger
     */
    ledger?: null | Ledger;
    /**
     * Order by
     */
    order_by?: InvoiceOrderBy;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/invoices';
};

export type DeleteInvoicesErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteInvoicesError = DeleteInvoicesErrors[keyof DeleteInvoicesErrors];

export type DeleteInvoicesResponses = {
  /**
   * Success
   */
  200: number;
};

export type DeleteInvoicesResponse = DeleteInvoicesResponses[keyof DeleteInvoicesResponses];

export type ListInvoicesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * Wallet ID. Automatically populated with your ID
     */
    wallet_id?: string | null;
    /**
     * Status
     */
    status?: null | InvoiceStatus;
    /**
     * Ledger
     */
    ledger?: null | Ledger;
    /**
     * Order by
     */
    order_by?: InvoiceOrderBy;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/invoices';
};

export type ListInvoicesErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type ListInvoicesError = ListInvoicesErrors[keyof ListInvoicesErrors];

export type ListInvoicesResponses = {
  /**
   * Success
   */
  200: Array<Invoice>;
};

export type ListInvoicesResponse = ListInvoicesResponses[keyof ListInvoicesResponses];

export type GenerateInvoiceData = {
  body: NewInvoiceRequest;
  path?: never;
  query?: never;
  url: '/v1/invoices';
};

export type GenerateInvoiceErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GenerateInvoiceError = GenerateInvoiceErrors[keyof GenerateInvoiceErrors];

export type GenerateInvoiceResponses = {
  /**
   * Invoice Created
   */
  200: Invoice;
};

export type GenerateInvoiceResponse = GenerateInvoiceResponses[keyof GenerateInvoiceResponses];

export type DeleteInvoiceData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/invoices/{id}';
};

export type DeleteInvoiceErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteInvoiceError = DeleteInvoiceErrors[keyof DeleteInvoiceErrors];

export type DeleteInvoiceResponses = {
  /**
   * Deleted
   */
  200: unknown;
};

export type GetInvoiceData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/invoices/{id}';
};

export type GetInvoiceErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetInvoiceError = GetInvoiceErrors[keyof GetInvoiceErrors];

export type GetInvoiceResponses = {
  /**
   * Found
   */
  200: Invoice;
};

export type GetInvoiceResponse = GetInvoiceResponses[keyof GetInvoiceResponses];

export type DeleteAddressesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * wallet ID. Automatically populated with your ID
     */
    wallet_id?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Active
     */
    active?: boolean | null;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/lightning-addresses';
};

export type DeleteAddressesErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteAddressesError = DeleteAddressesErrors[keyof DeleteAddressesErrors];

export type DeleteAddressesResponses = {
  /**
   * Success
   */
  200: number;
};

export type DeleteAddressesResponse = DeleteAddressesResponses[keyof DeleteAddressesResponses];

export type ListAddressesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * wallet ID. Automatically populated with your ID
     */
    wallet_id?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Active
     */
    active?: boolean | null;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/lightning-addresses';
};

export type ListAddressesErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type ListAddressesError = ListAddressesErrors[keyof ListAddressesErrors];

export type ListAddressesResponses = {
  /**
   * Success
   */
  200: Array<LnAddress>;
};

export type ListAddressesResponse = ListAddressesResponses[keyof ListAddressesResponses];

export type RegisterAddressData = {
  body: RegisterLnAddressRequest;
  path?: never;
  query?: never;
  url: '/v1/lightning-addresses';
};

export type RegisterAddressErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type RegisterAddressError = RegisterAddressErrors[keyof RegisterAddressErrors];

export type RegisterAddressResponses = {
  /**
   * LN Address Registered
   */
  200: LnAddress;
};

export type RegisterAddressResponse = RegisterAddressResponses[keyof RegisterAddressResponses];

export type DeleteAddressData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/lightning-addresses/{id}';
};

export type DeleteAddressErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteAddressError = DeleteAddressErrors[keyof DeleteAddressErrors];

export type DeleteAddressResponses = {
  /**
   * Deleted
   */
  200: unknown;
};

export type GetAddressData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/lightning-addresses/{id}';
};

export type GetAddressErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetAddressError = GetAddressErrors[keyof GetAddressErrors];

export type GetAddressResponses = {
  /**
   * Found
   */
  200: LnAddress;
};

export type GetAddressResponse = GetAddressResponses[keyof GetAddressResponses];

export type UpdateAddressData = {
  body: UpdateLnAddressRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/lightning-addresses/{id}';
};

export type UpdateAddressErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type UpdateAddressError = UpdateAddressErrors[keyof UpdateAddressErrors];

export type UpdateAddressResponses = {
  /**
   * LN Address Updated
   */
  200: LnAddress;
};

export type UpdateAddressResponse = UpdateAddressResponses[keyof UpdateAddressResponses];

export type GetUserWalletData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/me';
};

export type GetUserWalletErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetUserWalletError = GetUserWalletErrors[keyof GetUserWalletErrors];

export type GetUserWalletResponses = {
  /**
   * Found
   */
  200: Wallet;
};

export type GetUserWalletResponse = GetUserWalletResponses[keyof GetUserWalletResponses];

export type RevokeWalletApiKeysData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * Auth provider subject to filter by.
     *
     * User-scoped endpoints populate this with your own subject.
     */
    user_id?: string | null;
    /**
     * Owning account ID.
     */
    account_id?: string | null;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/me/api-keys';
};

export type RevokeWalletApiKeysErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type RevokeWalletApiKeysError = RevokeWalletApiKeysErrors[keyof RevokeWalletApiKeysErrors];

export type RevokeWalletApiKeysResponses = {
  /**
   * Success
   */
  200: number;
};

export type RevokeWalletApiKeysResponse =
  RevokeWalletApiKeysResponses[keyof RevokeWalletApiKeysResponses];

export type ListWalletApiKeysData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * Auth provider subject to filter by.
     *
     * User-scoped endpoints populate this with your own subject.
     */
    user_id?: string | null;
    /**
     * Owning account ID.
     */
    account_id?: string | null;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/me/api-keys';
};

export type ListWalletApiKeysErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type ListWalletApiKeysError = ListWalletApiKeysErrors[keyof ListWalletApiKeysErrors];

export type ListWalletApiKeysResponses = {
  /**
   * Success
   */
  200: Array<ApiKey>;
};

export type ListWalletApiKeysResponse =
  ListWalletApiKeysResponses[keyof ListWalletApiKeysResponses];

export type CreateWalletApiKeyData = {
  body: CreateApiKeyRequest;
  path?: never;
  query?: never;
  url: '/v1/me/api-keys';
};

export type CreateWalletApiKeyErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type CreateWalletApiKeyError = CreateWalletApiKeyErrors[keyof CreateWalletApiKeyErrors];

export type CreateWalletApiKeyResponses = {
  /**
   * API Key Created
   */
  200: ApiKey;
};

export type CreateWalletApiKeyResponse =
  CreateWalletApiKeyResponses[keyof CreateWalletApiKeyResponses];

export type RevokeWalletApiKeyData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/me/api-keys/{id}';
};

export type RevokeWalletApiKeyErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type RevokeWalletApiKeyError = RevokeWalletApiKeyErrors[keyof RevokeWalletApiKeyErrors];

export type RevokeWalletApiKeyResponses = {
  /**
   * Revoked
   */
  200: unknown;
};

export type GetWalletApiKeyData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/me/api-keys/{id}';
};

export type GetWalletApiKeyErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetWalletApiKeyError = GetWalletApiKeyErrors[keyof GetWalletApiKeyErrors];

export type GetWalletApiKeyResponses = {
  /**
   * Found
   */
  200: ApiKey;
};

export type GetWalletApiKeyResponse = GetWalletApiKeyResponses[keyof GetWalletApiKeyResponses];

export type GetWalletBalanceData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/me/balance';
};

export type GetWalletBalanceErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetWalletBalanceError = GetWalletBalanceErrors[keyof GetWalletBalanceErrors];

export type GetWalletBalanceResponses = {
  /**
   * Found
   */
  200: Balance;
};

export type GetWalletBalanceResponse = GetWalletBalanceResponses[keyof GetWalletBalanceResponses];

export type NewWalletBtcAddressData = {
  body: NewBtcAddressRequest;
  path?: never;
  query?: never;
  url: '/v1/me/bitcoin/address';
};

export type NewWalletBtcAddressErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type NewWalletBtcAddressError = NewWalletBtcAddressErrors[keyof NewWalletBtcAddressErrors];

export type NewWalletBtcAddressResponses = {
  /**
   * Bitcoin Address Created
   */
  200: BtcAddress;
};

export type NewWalletBtcAddressResponse =
  NewWalletBtcAddressResponses[keyof NewWalletBtcAddressResponses];

export type ListWalletBtcAddressesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * Wallet ID. Automatically populated with your ID
     */
    wallet_id?: string | null;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Status
     */
    address_type?: null | BtcAddressType;
    /**
     * Whether the address has been used
     */
    used?: boolean | null;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/me/bitcoin/addresses';
};

export type ListWalletBtcAddressesErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type ListWalletBtcAddressesError =
  ListWalletBtcAddressesErrors[keyof ListWalletBtcAddressesErrors];

export type ListWalletBtcAddressesResponses = {
  /**
   * Success
   */
  200: Array<BtcAddress>;
};

export type ListWalletBtcAddressesResponse =
  ListWalletBtcAddressesResponses[keyof ListWalletBtcAddressesResponses];

export type ListContactsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/me/contacts';
};

export type ListContactsErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type ListContactsError = ListContactsErrors[keyof ListContactsErrors];

export type ListContactsResponses = {
  /**
   * Success
   */
  200: Array<Contact>;
};

export type ListContactsResponse = ListContactsResponses[keyof ListContactsResponses];

export type DeleteExpiredInvoicesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/me/invoices';
};

export type DeleteExpiredInvoicesErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteExpiredInvoicesError =
  DeleteExpiredInvoicesErrors[keyof DeleteExpiredInvoicesErrors];

export type DeleteExpiredInvoicesResponses = {
  /**
   * Success
   */
  200: number;
};

export type DeleteExpiredInvoicesResponse =
  DeleteExpiredInvoicesResponses[keyof DeleteExpiredInvoicesResponses];

export type ListWalletInvoicesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * Wallet ID. Automatically populated with your ID
     */
    wallet_id?: string | null;
    /**
     * Status
     */
    status?: null | InvoiceStatus;
    /**
     * Ledger
     */
    ledger?: null | Ledger;
    /**
     * Order by
     */
    order_by?: InvoiceOrderBy;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/me/invoices';
};

export type ListWalletInvoicesErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type ListWalletInvoicesError = ListWalletInvoicesErrors[keyof ListWalletInvoicesErrors];

export type ListWalletInvoicesResponses = {
  /**
   * Success
   */
  200: Array<Invoice>;
};

export type ListWalletInvoicesResponse =
  ListWalletInvoicesResponses[keyof ListWalletInvoicesResponses];

export type NewWalletInvoiceData = {
  body: NewInvoiceRequest;
  path?: never;
  query?: never;
  url: '/v1/me/invoices';
};

export type NewWalletInvoiceErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type NewWalletInvoiceError = NewWalletInvoiceErrors[keyof NewWalletInvoiceErrors];

export type NewWalletInvoiceResponses = {
  /**
   * Invoice Created
   */
  200: Invoice;
};

export type NewWalletInvoiceResponse = NewWalletInvoiceResponses[keyof NewWalletInvoiceResponses];

export type GetWalletInvoiceData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/me/invoices/{id}';
};

export type GetWalletInvoiceErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetWalletInvoiceError = GetWalletInvoiceErrors[keyof GetWalletInvoiceErrors];

export type GetWalletInvoiceResponses = {
  /**
   * Found
   */
  200: Invoice;
};

export type GetWalletInvoiceResponse = GetWalletInvoiceResponses[keyof GetWalletInvoiceResponses];

export type DeleteWalletAddressData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/me/lightning-address';
};

export type DeleteWalletAddressErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteWalletAddressError = DeleteWalletAddressErrors[keyof DeleteWalletAddressErrors];

export type DeleteWalletAddressResponses = {
  /**
   * Deleted
   */
  200: unknown;
};

export type GetWalletAddressData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/me/lightning-address';
};

export type GetWalletAddressErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetWalletAddressError = GetWalletAddressErrors[keyof GetWalletAddressErrors];

export type GetWalletAddressResponses = {
  /**
   * Found
   */
  200: null | LnAddress;
};

export type GetWalletAddressResponse = GetWalletAddressResponses[keyof GetWalletAddressResponses];

export type RegisterWalletAddressData = {
  body: RegisterLnAddressRequest;
  path?: never;
  query?: never;
  url: '/v1/me/lightning-address';
};

export type RegisterWalletAddressErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type RegisterWalletAddressError =
  RegisterWalletAddressErrors[keyof RegisterWalletAddressErrors];

export type RegisterWalletAddressResponses = {
  /**
   * LN Address Registered
   */
  200: LnAddress;
};

export type RegisterWalletAddressResponse =
  RegisterWalletAddressResponses[keyof RegisterWalletAddressResponses];

export type UpdateWalletAddressData = {
  body: UpdateLnAddressRequest;
  path?: never;
  query?: never;
  url: '/v1/me/lightning-address';
};

export type UpdateWalletAddressErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type UpdateWalletAddressError = UpdateWalletAddressErrors[keyof UpdateWalletAddressErrors];

export type UpdateWalletAddressResponses = {
  /**
   * LN Address Updated
   */
  200: LnAddress;
};

export type UpdateWalletAddressResponse =
  UpdateWalletAddressResponses[keyof UpdateWalletAddressResponses];

export type DeleteFailedPaymentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/me/payments';
};

export type DeleteFailedPaymentsErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteFailedPaymentsError =
  DeleteFailedPaymentsErrors[keyof DeleteFailedPaymentsErrors];

export type DeleteFailedPaymentsResponses = {
  /**
   * Success
   */
  200: number;
};

export type DeleteFailedPaymentsResponse =
  DeleteFailedPaymentsResponses[keyof DeleteFailedPaymentsResponses];

export type ListWalletPaymentsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * Wallet ID. Automatically populated with your ID
     */
    wallet_id?: string | null;
    /**
     * Status
     */
    status?: null | PaymentStatus;
    /**
     * Ledger
     */
    ledger?: null | Ledger;
    /**
     * Lightning addresses
     */
    ln_addresses?: Array<string> | null;
    /**
     * Bitcoin addresses
     */
    btc_addresses?: Array<string> | null;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/me/payments';
};

export type ListWalletPaymentsErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type ListWalletPaymentsError = ListWalletPaymentsErrors[keyof ListWalletPaymentsErrors];

export type ListWalletPaymentsResponses = {
  /**
   * Success
   */
  200: Array<Payment>;
};

export type ListWalletPaymentsResponse =
  ListWalletPaymentsResponses[keyof ListWalletPaymentsResponses];

export type WalletPayData = {
  body: SendPaymentRequest;
  path?: never;
  query?: never;
  url: '/v1/me/payments';
};

export type WalletPayErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type WalletPayError = WalletPayErrors[keyof WalletPayErrors];

export type WalletPayResponses = {
  /**
   * Payment Sent
   */
  200: Payment;
};

export type WalletPayResponse = WalletPayResponses[keyof WalletPayResponses];

export type GetWalletPaymentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/me/payments/{id}';
};

export type GetWalletPaymentErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetWalletPaymentError = GetWalletPaymentErrors[keyof GetWalletPaymentErrors];

export type GetWalletPaymentResponses = {
  /**
   * Found
   */
  200: Payment;
};

export type GetWalletPaymentResponse = GetWalletPaymentResponses[keyof GetWalletPaymentResponses];

export type DeletePaymentsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * Wallet ID. Automatically populated with your ID
     */
    wallet_id?: string | null;
    /**
     * Status
     */
    status?: null | PaymentStatus;
    /**
     * Ledger
     */
    ledger?: null | Ledger;
    /**
     * Lightning addresses
     */
    ln_addresses?: Array<string> | null;
    /**
     * Bitcoin addresses
     */
    btc_addresses?: Array<string> | null;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/payments';
};

export type DeletePaymentsErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeletePaymentsError = DeletePaymentsErrors[keyof DeletePaymentsErrors];

export type DeletePaymentsResponses = {
  /**
   * Success
   */
  200: number;
};

export type DeletePaymentsResponse = DeletePaymentsResponses[keyof DeletePaymentsResponses];

export type ListPaymentsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * Wallet ID. Automatically populated with your ID
     */
    wallet_id?: string | null;
    /**
     * Status
     */
    status?: null | PaymentStatus;
    /**
     * Ledger
     */
    ledger?: null | Ledger;
    /**
     * Lightning addresses
     */
    ln_addresses?: Array<string> | null;
    /**
     * Bitcoin addresses
     */
    btc_addresses?: Array<string> | null;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/payments';
};

export type ListPaymentsErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type ListPaymentsError = ListPaymentsErrors[keyof ListPaymentsErrors];

export type ListPaymentsResponses = {
  /**
   * Success
   */
  200: Array<Payment>;
};

export type ListPaymentsResponse = ListPaymentsResponses[keyof ListPaymentsResponses];

export type PayData = {
  body: SendPaymentRequest;
  path?: never;
  query?: never;
  url: '/v1/payments';
};

export type PayErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PayError = PayErrors[keyof PayErrors];

export type PayResponses = {
  /**
   * Payment Sent
   */
  200: Payment;
};

export type PayResponse = PayResponses[keyof PayResponses];

export type DeletePaymentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/payments/{id}';
};

export type DeletePaymentErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeletePaymentError = DeletePaymentErrors[keyof DeletePaymentErrors];

export type DeletePaymentResponses = {
  /**
   * Deleted
   */
  200: unknown;
};

export type GetPaymentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/payments/{id}';
};

export type GetPaymentErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetPaymentError = GetPaymentErrors[keyof GetPaymentErrors];

export type GetPaymentResponses = {
  /**
   * Found
   */
  200: Payment;
};

export type GetPaymentResponse = GetPaymentResponses[keyof GetPaymentResponses];

export type HealthCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/system/health';
};

export type HealthCheckErrors = {
  /**
   * Service Unavailable
   */
  503: HealthCheck;
};

export type HealthCheckError = HealthCheckErrors[keyof HealthCheckErrors];

export type HealthCheckResponses = {
  /**
   * OK
   */
  200: HealthCheck;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type MarkWelcomeCompleteData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/system/mark-welcome-complete';
};

export type MarkWelcomeCompleteErrors = {
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type MarkWelcomeCompleteError = MarkWelcomeCompleteErrors[keyof MarkWelcomeCompleteErrors];

export type MarkWelcomeCompleteResponses = {
  /**
   * No Content on success
   */
  204: void;
};

export type MarkWelcomeCompleteResponse =
  MarkWelcomeCompleteResponses[keyof MarkWelcomeCompleteResponses];

export type ReadinessCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/system/ready';
};

export type ReadinessCheckResponses = {
  /**
   * No Content on success
   */
  204: void;
};

export type ReadinessCheckResponse = ReadinessCheckResponses[keyof ReadinessCheckResponses];

export type SetupCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/system/setup';
};

export type SetupCheckErrors = {
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type SetupCheckError = SetupCheckErrors[keyof SetupCheckErrors];

export type SetupCheckResponses = {
  /**
   * OK
   */
  200: SetupInfo;
};

export type SetupCheckResponse = SetupCheckResponses[keyof SetupCheckResponses];

export type VersionCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/system/version';
};

export type VersionCheckResponses = {
  /**
   * OK
   */
  200: VersionInfo;
};

export type VersionCheckResponse = VersionCheckResponses[keyof VersionCheckResponses];

export type DeleteWalletsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Total amount of results to return
     */
    limit?: number | null;
    /**
     * Offset where to start returning results
     */
    offset?: number | null;
    /**
     * List of IDs
     */
    ids?: Array<string> | null;
    /**
     * Owning account ID
     */
    account_id?: string | null;
    /**
     * Asset ID
     */
    asset_id?: string | null;
    /**
     * Direction of the ordering of results
     */
    order_direction?: OrderDirection;
  };
  url: '/v1/wallets';
};

export type DeleteWalletsErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteWalletsError = DeleteWalletsErrors[keyof DeleteWalletsErrors];

export type DeleteWalletsResponses = {
  /**
   * Success
   */
  200: number;
};

export type DeleteWalletsResponse = DeleteWalletsResponses[keyof DeleteWalletsResponses];

export type ListWalletsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/wallets';
};

export type ListWalletsErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type ListWalletsError = ListWalletsErrors[keyof ListWalletsErrors];

export type ListWalletsResponses = {
  /**
   * Success
   */
  200: Array<Wallet>;
};

export type ListWalletsResponse = ListWalletsResponses[keyof ListWalletsResponses];

export type RegisterWalletData = {
  body: CreateWalletRequest;
  path?: never;
  query?: never;
  url: '/v1/wallets';
};

export type RegisterWalletErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type RegisterWalletError = RegisterWalletErrors[keyof RegisterWalletErrors];

export type RegisterWalletResponses = {
  /**
   * Wallet Created
   */
  200: Wallet;
};

export type RegisterWalletResponse = RegisterWalletResponses[keyof RegisterWalletResponses];

export type ListWalletOverviewsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/wallets/overviews';
};

export type ListWalletOverviewsErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type ListWalletOverviewsError = ListWalletOverviewsErrors[keyof ListWalletOverviewsErrors];

export type ListWalletOverviewsResponses = {
  /**
   * Success
   */
  200: Array<WalletOverview>;
};

export type ListWalletOverviewsResponse =
  ListWalletOverviewsResponses[keyof ListWalletOverviewsResponses];

export type DeleteWalletData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/wallets/{id}';
};

export type DeleteWalletErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteWalletError = DeleteWalletErrors[keyof DeleteWalletErrors];

export type DeleteWalletResponses = {
  /**
   * Deleted
   */
  200: unknown;
};

export type GetWalletData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/v1/wallets/{id}';
};

export type GetWalletErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetWalletError = GetWalletErrors[keyof GetWalletErrors];

export type GetWalletResponses = {
  /**
   * Found
   */
  200: Wallet;
};

export type GetWalletResponse = GetWalletResponses[keyof GetWalletResponses];
