// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Asset settlement network.
 */
export const zAssetNetwork = z.enum([
  'bitcoin/mainnet',
  'bitcoin/testnet',
  'bitcoin/testnet4',
  'bitcoin/regtest',
  'bitcoin/simnet',
  'bitcoin/signet',
]);

/**
 * Asset settlement protocol.
 */
export const zAssetProtocol = z.enum(['bitcoin', 'taproot_assets']);

/**
 * A spendable asset on one protocol/network.
 */
export const zAsset = z.object({
  asset_ref: z.string(),
  code: z.string(),
  created_at: z.iso.datetime(),
  decimals: z
    .int()
    .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  display_ticker: z.string(),
  id: z.uuid(),
  name: z.string().nullish(),
  network: zAssetNetwork,
  protocol: zAssetProtocol,
  updated_at: z.iso.datetime().nullish(),
});

/**
 * A wallet's balance, in millisatoshis.
 */
export const zBalance = z.object({
  available_msat: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  fees_paid_msat: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  }),
  received_msat: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  }),
  reserved_msat: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  }),
  sent_msat: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  }),
});

/**
 * Bitcoin address script type.
 */
export const zBtcAddressType = z.enum(['p2pkh', 'p2sh', 'p2wpkh', 'p2tr']);

/**
 * Bitcoin Address
 */
export const zBtcAddress = z.object({
  address: z.string(),
  address_type: zBtcAddressType,
  created_at: z.iso.datetime(),
  id: z.uuid(),
  updated_at: z.iso.datetime().nullish(),
  used: z.boolean(),
  wallet_id: z.uuid(),
});

/**
 * A Bitcoin network.
 */
export const zBtcNetwork = z.enum([
  'Bitcoin',
  'Testnet',
  'Testnet4',
  'Regtest',
  'Simnet',
  'Signet',
]);

/**
 * Confirmation status of an on-chain output.
 */
export const zBtcOutputStatus = z.enum(['Unconfirmed', 'Confirmed', 'Spent', 'Immature']);

/**
 * Bitcoin Output
 */
export const zBtcOutput = z.object({
  address: z.string(),
  amount_sat: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  }),
  block_height: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  created_at: z.iso.datetime(),
  id: z.uuid(),
  outpoint: z.string(),
  status: zBtcOutputStatus,
  updated_at: z.iso.datetime().nullish(),
});

/**
 * On-chain Bitcoin details of a payment.
 */
export const zBtcPayment = z.object({
  address: z.string(),
  block_height: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  txid: z.string(),
});

/**
 * Change Password Request
 */
export const zChangePasswordRequest = z.object({
  current_password: z.string(),
  new_password: z.string(),
});

/**
 * A counterparty the wallet has paid, with the date of first contact.
 */
export const zContact = z.object({
  contact_since: z.iso.datetime(),
  ln_address: z.string(),
});

/**
 * Create Wallet Request
 */
export const zCreateWalletRequest = z.object({
  account_id: z.uuid(),
  asset_id: z.uuid(),
});

/**
 * The currency and network a transaction is denominated in.
 */
export const zCurrency = z.enum(['Bitcoin', 'BitcoinTestnet', 'Regtest', 'Simnet', 'Signet']);

/**
 * Application error response
 */
export const zErrorResponse = z.object({
  reason: z.string(),
  status: z.string(),
});

/**
 * Health of a single system dependency.
 */
export const zHealthStatus = z.enum(['Operational', 'Unavailable', 'Maintenance']);

/**
 * App health information, fine-grained by dependency.
 */
export const zHealthCheck = z.object({
  database: zHealthStatus,
  is_healthy: z.boolean(),
  ln_provider: zHealthStatus,
});

/**
 * Details of a payment settled internally between wallets on the same instance.
 */
export const zInternalPayment = z.object({
  btc_address: z.string().nullish(),
  ln_address: z.string().nullish(),
  payment_hash: z.string().nullish(),
});

/**
 * Field to order invoices by.
 */
export const zInvoiceOrderBy = z.enum(['CreatedAt', 'PaymentTime', 'UpdatedAt']);

/**
 * Lifecycle status of an invoice.
 */
export const zInvoiceStatus = z.enum(['Pending', 'Settled', 'Expired']);

/**
 * The ledger a transaction settles on.
 */
export const zLedger = z.enum(['Lightning', 'Internal', 'Onchain']);

/**
 * Lightning Address
 */
export const zLnAddress = z.object({
  active: z.boolean(),
  allows_nostr: z.boolean(),
  created_at: z.iso.datetime(),
  id: z.uuid(),
  nostr_pubkey: z.string().nullish(),
  updated_at: z.iso.datetime().nullish(),
  username: z.string(),
  wallet_id: z.uuid(),
});

/**
 * Lightning-specific details of an invoice.
 */
export const zLnInvoice = z.object({
  bolt11: z.string(),
  description_hash: z.string().nullish(),
  expires_at: z.iso.datetime(),
  expiry: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  }),
  min_final_cltv_expiry_delta: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  }),
  payee_pubkey: z.string(),
  payment_hash: z.string(),
  payment_secret: z.string(),
});

/**
 * An incoming payment request, over Lightning and/or on-chain.
 */
export const zInvoice = z.object({
  amount_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  amount_received_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  bitcoin_output: zBtcOutput.nullish(),
  created_at: z.iso.datetime(),
  currency: zCurrency,
  description: z.string().nullish(),
  fee_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  id: z.uuid(),
  ledger: zLedger,
  ln_address_id: z.uuid().nullish(),
  ln_invoice: zLnInvoice.nullish(),
  payment_time: z.iso.datetime().nullish(),
  status: zInvoiceStatus,
  timestamp: z.iso.datetime(),
  updated_at: z.iso.datetime().nullish(),
  wallet_id: z.uuid(),
});

/**
 * LNURL-pay `payRequest` response served at the well-known endpoint (LUD-06).
 */
export const zLnUrlPayRequest = z.object({
  allowsNostr: z.boolean(),
  callback: z.string(),
  commentAllowed: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  maxSendable: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  }),
  metadata: z.string(),
  minSendable: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  }),
  nostrPubkey: z.string().nullish(),
  tag: z.string(),
});

/**
 * LNURL success action shown to the payer after a successful payment (LUD-09).
 */
export const zLnUrlSuccessAction = z.object({
  description: z.string().nullish(),
  message: z.string().nullish(),
  tag: z.string(),
  url: z.string().nullish(),
});

/**
 * Lightning-specific details of a payment.
 */
export const zLnPayment = z.object({
  ln_address: z.string().nullish(),
  metadata: z.string().nullish(),
  payment_hash: z.string(),
  payment_preimage: z.string().nullish(),
  success_action: zLnUrlSuccessAction.nullish(),
});

/**
 * LNURL-pay callback response. Carries the invoice to pay and how to behave on
 * success. Wire shape follows LUD-06 (camelCase fields).
 */
export const zLnUrlCallback = z.object({
  disposable: z.boolean().nullish(),
  pr: z.string(),
  routes: z.array(z.string()),
  successAction: zLnUrlSuccessAction.nullish(),
});

/**
 * New Bitcoin Address Request
 */
export const zNewBtcAddressRequest = z.object({
  type: zBtcAddressType.nullish(),
  wallet_id: z.uuid().nullish(),
});

/**
 * New Invoice Request
 */
export const zNewInvoiceRequest = z.object({
  amount_msat: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  }),
  description: z.string().nullish(),
  expiry: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  wallet_id: z.uuid().nullish(),
});

/**
 * Nostr NIP-05 response. Maps each queried name to its hex-encoded public key.
 */
export const zNostrNip05Response = z.object({
  names: z.record(z.string(), z.string()),
});

/**
 * Direction of result ordering for list endpoints.
 */
export const zOrderDirection = z.enum(['Asc', 'Desc']);

/**
 * Lifecycle status of a payment.
 */
export const zPaymentStatus = z.enum(['Pending', 'Settled', 'Failed']);

/**
 * An outgoing payment, over Lightning, on-chain, or internal to the instance.
 */
export const zPayment = z.object({
  amount_msat: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  }),
  bitcoin: zBtcPayment.nullish(),
  created_at: z.iso.datetime(),
  currency: zCurrency,
  description: z.string().nullish(),
  error: z.string().nullish(),
  fee_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  id: z.uuid(),
  internal: zInternalPayment.nullish(),
  ledger: zLedger,
  lightning: zLnPayment.nullish(),
  payment_time: z.iso.datetime().nullish(),
  status: zPaymentStatus,
  updated_at: z.iso.datetime().nullish(),
  wallet_id: z.uuid(),
});

/**
 * An API access scope granted to a JWT or API key.
 */
export const zPermission = z.enum([
  'read:wallet',
  'write:wallet',
  'read:ln_address',
  'write:ln_address',
  'read:transaction',
  'write:transaction',
  'read:ln_node',
  'write:ln_node',
  'read:api_key',
  'write:api_key',
  'read:btc_address',
  'write:btc_address',
]);

/**
 * API Key
 */
export const zApiKey = z.object({
  account_id: z.uuid(),
  created_at: z.iso.datetime(),
  description: z.string().nullish(),
  expires_at: z.iso.datetime().nullish(),
  id: z.uuid(),
  key: z.string().nullish(),
  name: z.string(),
  permissions: z.array(zPermission),
});

/**
 * Create API Key Request
 */
export const zCreateApiKeyRequest = z.object({
  account_id: z.uuid().nullish(),
  description: z.string().nullish(),
  expiry: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  name: z.string(),
  permissions: z.array(zPermission),
});

/**
 * Register Lightning Address Request
 */
export const zRegisterLnAddressRequest = z.object({
  allows_nostr: z.boolean().optional(),
  nostr_pubkey: z.string().nullish(),
  username: z.string(),
  wallet_id: z.uuid().nullish(),
});

/**
 * Send Payment Request
 */
export const zSendPaymentRequest = z.object({
  amount_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  comment: z.string().nullish(),
  input: z.string(),
  wallet_id: z.uuid().nullish(),
});

/**
 * App setup info.
 */
export const zSetupInfo = z.object({
  sign_up_complete: z.boolean(),
  welcome_complete: z.boolean(),
});

/**
 * Sign In Request
 */
export const zSignInRequest = z.object({
  password: z.string(),
});

/**
 * Sign In Response
 */
export const zSignInResponse = z.object({
  token: z.string(),
});

/**
 * Sign Up Request
 */
export const zSignUpRequest = z.object({
  password: z.string(),
});

/**
 * Update Lightning Address Request
 */
export const zUpdateLnAddressRequest = z.object({
  active: z.boolean().nullish(),
  allows_nostr: z.boolean().nullish(),
  nostr_pubkey: z.string().nullish(),
  username: z.string().nullish(),
});

/**
 * App version info.
 */
export const zVersionInfo = z.object({
  build_time: z.string(),
  version: z.string(),
});

/**
 * A user wallet with its balance and linked payments, invoices, Bitcoin addresses and contacts.
 */
export const zWallet = z.object({
  account_id: z.uuid(),
  asset: zAsset.nullish(),
  asset_id: z.uuid(),
  balance: zBalance,
  btc_addresses: z.array(zBtcAddress),
  contacts: z.array(zContact),
  created_at: z.iso.datetime(),
  id: z.uuid(),
  invoices: z.array(zInvoice),
  label: z.string().nullish(),
  ln_address: zLnAddress.nullish(),
  payments: z.array(zPayment),
  updated_at: z.iso.datetime().nullish(),
});

/**
 * A lightweight wallet summary with counts in place of the full lists.
 */
export const zWalletOverview = z.object({
  account_id: z.uuid(),
  asset: zAsset.nullish(),
  asset_id: z.uuid(),
  balance: zBalance,
  created_at: z.iso.datetime(),
  id: z.uuid(),
  label: z.string().nullish(),
  ln_address: zLnAddress.nullish(),
  n_contacts: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  n_invoices: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  n_payments: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  updated_at: z.iso.datetime().nullish(),
});

export const zWellKnownPath = z.object({
  username: z.string(),
});

/**
 * Found
 */
export const zWellKnownResponse = zLnUrlPayRequest;

export const zWellKnownNostrQuery = z.object({
  name: z.string().optional(),
});

/**
 * Found
 */
export const zWellKnownNostrResponse = zNostrNip05Response;

export const zCallbackPath = z.object({
  username: z.string(),
});

export const zCallbackQuery = z.object({
  amount: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  }),
  comment: z.string().nullish(),
});

/**
 * Found
 */
export const zCallbackResponse = zLnUrlCallback;

export const zRevokeApiKeysQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  account_id: z.uuid().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zRevokeApiKeysResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

export const zListApiKeysQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  account_id: z.uuid().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListApiKeysResponse = z.array(zApiKey);

export const zCreateApiKeyBody = zCreateApiKeyRequest;

/**
 * API Key Created
 */
export const zCreateApiKeyResponse = zApiKey;

export const zRevokeApiKeyPath = z.object({
  id: z.uuid(),
});

export const zGetApiKeyPath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetApiKeyResponse = zApiKey;

export const zChangePasswordBody = zChangePasswordRequest;

/**
 * Password changed
 */
export const zChangePasswordResponse = z.void();

export const zSignInBody = zSignInRequest;

/**
 * Token Created
 */
export const zSignInResponse2 = zSignInResponse;

export const zSignUpBody = zSignUpRequest;

/**
 * Admin user created
 */
export const zSignUpResponse = zSignInResponse;

export const zDeleteBtcAddressesQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  address: z.string().nullish(),
  address_type: zBtcAddressType.nullish(),
  used: z.boolean().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zDeleteBtcAddressesResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

export const zListBtcAddressesQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  address: z.string().nullish(),
  address_type: zBtcAddressType.nullish(),
  used: z.boolean().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListBtcAddressesResponse = z.array(zBtcAddress);

export const zGenerateBtcAddressBody = zNewBtcAddressRequest;

/**
 * Bitcoin Address Created
 */
export const zGenerateBtcAddressResponse = zBtcAddress;

export const zDeleteBtcAddressPath = z.object({
  id: z.uuid(),
});

export const zGetBtcAddressPath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetBtcAddressResponse = zBtcAddress;

export const zDeleteInvoicesQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  status: zInvoiceStatus.nullish(),
  ledger: zLedger.nullish(),
  order_by: zInvoiceOrderBy.optional(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zDeleteInvoicesResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

export const zListInvoicesQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  status: zInvoiceStatus.nullish(),
  ledger: zLedger.nullish(),
  order_by: zInvoiceOrderBy.optional(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListInvoicesResponse = z.array(zInvoice);

export const zGenerateInvoiceBody = zNewInvoiceRequest;

/**
 * Invoice Created
 */
export const zGenerateInvoiceResponse = zInvoice;

export const zDeleteInvoicePath = z.object({
  id: z.uuid(),
});

export const zGetInvoicePath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetInvoiceResponse = zInvoice;

export const zDeleteAddressesQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  username: z.string().nullish(),
  active: z.boolean().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zDeleteAddressesResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

export const zListAddressesQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  username: z.string().nullish(),
  active: z.boolean().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListAddressesResponse = z.array(zLnAddress);

export const zRegisterAddressBody = zRegisterLnAddressRequest;

/**
 * LN Address Registered
 */
export const zRegisterAddressResponse = zLnAddress;

export const zDeleteAddressPath = z.object({
  id: z.uuid(),
});

export const zGetAddressPath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetAddressResponse = zLnAddress;

export const zUpdateAddressBody = zUpdateLnAddressRequest;

export const zUpdateAddressPath = z.object({
  id: z.uuid(),
});

/**
 * LN Address Updated
 */
export const zUpdateAddressResponse = zLnAddress;

/**
 * Found
 */
export const zGetUserWalletResponse = zWallet;

export const zRevokeWalletApiKeysQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  account_id: z.uuid().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zRevokeWalletApiKeysResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

export const zListWalletApiKeysQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  account_id: z.uuid().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListWalletApiKeysResponse = z.array(zApiKey);

export const zCreateWalletApiKeyBody = zCreateApiKeyRequest;

/**
 * API Key Created
 */
export const zCreateWalletApiKeyResponse = zApiKey;

export const zRevokeWalletApiKeyPath = z.object({
  id: z.uuid(),
});

export const zGetWalletApiKeyPath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetWalletApiKeyResponse = zApiKey;

/**
 * Found
 */
export const zGetWalletBalanceResponse = zBalance;

export const zNewWalletBtcAddressBody = zNewBtcAddressRequest;

/**
 * Bitcoin Address Created
 */
export const zNewWalletBtcAddressResponse = zBtcAddress;

export const zListWalletBtcAddressesQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  address: z.string().nullish(),
  address_type: zBtcAddressType.nullish(),
  used: z.boolean().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListWalletBtcAddressesResponse = z.array(zBtcAddress);

/**
 * Success
 */
export const zListContactsResponse = z.array(zContact);

/**
 * Success
 */
export const zDeleteExpiredInvoicesResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

export const zListWalletInvoicesQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  status: zInvoiceStatus.nullish(),
  ledger: zLedger.nullish(),
  order_by: zInvoiceOrderBy.optional(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListWalletInvoicesResponse = z.array(zInvoice);

export const zNewWalletInvoiceBody = zNewInvoiceRequest;

/**
 * Invoice Created
 */
export const zNewWalletInvoiceResponse = zInvoice;

export const zGetWalletInvoicePath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetWalletInvoiceResponse = zInvoice;

/**
 * Found
 */
export const zGetWalletAddressResponse = zLnAddress.nullable();

export const zRegisterWalletAddressBody = zRegisterLnAddressRequest;

/**
 * LN Address Registered
 */
export const zRegisterWalletAddressResponse = zLnAddress;

export const zUpdateWalletAddressBody = zUpdateLnAddressRequest;

/**
 * LN Address Updated
 */
export const zUpdateWalletAddressResponse = zLnAddress;

/**
 * Success
 */
export const zDeleteFailedPaymentsResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

export const zListWalletPaymentsQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  status: zPaymentStatus.nullish(),
  ledger: zLedger.nullish(),
  ln_addresses: z.array(z.string()).nullish(),
  btc_addresses: z.array(z.string()).nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListWalletPaymentsResponse = z.array(zPayment);

export const zWalletPayBody = zSendPaymentRequest;

/**
 * Payment Sent
 */
export const zWalletPayResponse = zPayment;

export const zGetWalletPaymentPath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetWalletPaymentResponse = zPayment;

export const zDeletePaymentsQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  status: zPaymentStatus.nullish(),
  ledger: zLedger.nullish(),
  ln_addresses: z.array(z.string()).nullish(),
  btc_addresses: z.array(z.string()).nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zDeletePaymentsResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

export const zListPaymentsQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  status: zPaymentStatus.nullish(),
  ledger: zLedger.nullish(),
  ln_addresses: z.array(z.string()).nullish(),
  btc_addresses: z.array(z.string()).nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListPaymentsResponse = z.array(zPayment);

export const zPayBody = zSendPaymentRequest;

/**
 * Payment Sent
 */
export const zPayResponse = zPayment;

export const zDeletePaymentPath = z.object({
  id: z.uuid(),
});

export const zGetPaymentPath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetPaymentResponse = zPayment;

/**
 * OK
 */
export const zHealthCheckResponse = zHealthCheck;

/**
 * No Content on success
 */
export const zMarkWelcomeCompleteResponse = z.void();

/**
 * No Content on success
 */
export const zReadinessCheckResponse = z.void();

/**
 * OK
 */
export const zSetupCheckResponse = zSetupInfo;

/**
 * OK
 */
export const zVersionCheckResponse = zVersionInfo;

export const zDeleteWalletsQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  account_id: z.uuid().nullish(),
  asset_id: z.uuid().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zDeleteWalletsResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

/**
 * Success
 */
export const zListWalletsResponse = z.array(zWallet);

export const zRegisterWalletBody = zCreateWalletRequest;

/**
 * Wallet Created
 */
export const zRegisterWalletResponse = zWallet;

/**
 * Success
 */
export const zListWalletOverviewsResponse = z.array(zWalletOverview);

export const zDeleteWalletPath = z.object({
  id: z.uuid(),
});

export const zGetWalletPath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetWalletResponse = zWallet;
