// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zBalance = z.object({
  available_msat: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  fees_paid_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  received_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  sent_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
});

export const zCheckMessageRequest = z.object({
  message: z.string(),
  pubkey: z.string(),
  signature: z.string(),
});

export const zCheckMessageResponse = z.object({
  is_valid: z.boolean(),
});

export const zContact = z.object({
  contact_since: z.iso.datetime(),
  ln_address: z.string(),
});

export const zCurrency = z.enum(['Bitcoin', 'BitcoinTestnet', 'Regtest', 'Simnet', 'Signet']);

/**
 * Application Error Response
 */
export const zErrorResponse = z.object({
  reason: z.string(),
  status: z.string(),
});

export const zHealthStatus = z.enum(['Operational', 'Unavailable', 'Maintenance']);

/**
 * App Health Information
 */
export const zHealthCheck = z.object({
  database: zHealthStatus,
  is_healthy: z.boolean(),
  ln_provider: zHealthStatus,
});

export const zInvoiceOrderBy = z.enum(['CreatedAt', 'PaymentTime', 'UpdatedAt']);

export const zInvoiceStatus = z.enum(['Pending', 'Settled', 'Expired']);

export const zLedger = z.enum(['Lightning', 'Internal', 'Onchain']);

/**
 * Lightning Address
 */
export const zLnAddress = z.object({
  active: z.boolean(),
  allows_nostr: z.boolean(),
  created_at: z.iso.datetime(),
  id: z.uuid(),
  nostr_pubkey: z.string().nullish(),
  updated_at: z.iso.datetime().nullish(),
  username: z.string(),
  wallet_id: z.uuid(),
});

export const zLnInvoiceResponse = z.object({
  bolt11: z.string(),
  description_hash: z.string().nullish(),
  expires_at: z.iso.datetime(),
  expiry: z.string(),
  min_final_cltv_expiry_delta: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  payee_pubkey: z.string(),
  payment_hash: z.string(),
  payment_secret: z.string(),
});

export const zInvoiceResponse = z.object({
  amount_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  amount_received_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  created_at: z.iso.datetime(),
  currency: zCurrency,
  description: z.string().nullish(),
  fee_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  id: z.uuid(),
  ledger: zLedger,
  ln_address_id: z.uuid().nullish(),
  ln_invoice: zLnInvoiceResponse.nullish(),
  payment_time: z.iso.datetime().nullish(),
  status: zInvoiceStatus,
  timestamp: z.iso.datetime(),
  updated_at: z.iso.datetime().nullish(),
  wallet_id: z.uuid(),
});

export const zLnUrlPayRequest = z.object({
  allowsNostr: z.boolean(),
  callback: z.string(),
  commentAllowed: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  maxSendable: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  metadata: z.string(),
  minSendable: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  nostrPubkey: z.string().nullish(),
  tag: z.string(),
});

export const zLnUrlCallbackResponse = z.object({
  disposable: z.boolean().nullish(),
  pr: z.string(),
  routes: z.array(z.string()),
  successAction: z.unknown().optional(),
});

export const zLnUrlSuccessAction = z.object({
  description: z.string().nullish(),
  message: z.string().nullish(),
  tag: z.string(),
  url: z.string().nullish(),
});

/**
 * New Invoice Request
 */
export const zNewInvoiceRequest = z.object({
  amount_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  description: z.string().nullish(),
  expiry: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  wallet_id: z.uuid().nullish(),
});

export const zNostrNip05Response = z.object({
  names: z.record(z.string(), z.string()),
});

export const zOrderDirection = z.enum(['Asc', 'Desc']);

export const zPaymentStatus = z.enum(['Pending', 'Settled', 'Failed']);

export const zPaymentResponse = z.object({
  amount_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  created_at: z.iso.datetime(),
  currency: zCurrency,
  description: z.string().nullish(),
  error: z.string().nullish(),
  fee_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  id: z.uuid(),
  ledger: zLedger,
  ln_address: z.string().nullish(),
  metadata: z.string().nullish(),
  payment_hash: z.string().nullish(),
  payment_preimage: z.string().nullish(),
  payment_time: z.iso.datetime().nullish(),
  status: zPaymentStatus,
  success_action: zLnUrlSuccessAction.nullish(),
  updated_at: z.iso.datetime().nullish(),
  wallet_id: z.uuid(),
});

export const zPermission = z.enum([
  'read:wallet',
  'write:wallet',
  'read:ln_address',
  'write:ln_address',
  'read:transaction',
  'write:transaction',
  'read:ln_node',
  'write:ln_node',
  'read:api_key',
  'write:api_key',
]);

/**
 * API Key Response
 */
export const zApiKeyResponse = z.object({
  created_at: z.iso.datetime(),
  description: z.string().nullish(),
  expires_at: z.iso.datetime().nullish(),
  id: z.uuid(),
  key: z.string().nullish(),
  name: z.string(),
  permissions: z.array(zPermission),
  user_id: z.string(),
});

/**
 * Create API Key Request
 */
export const zCreateApiKeyRequest = z.object({
  description: z.string().nullish(),
  expiry: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  name: z.string(),
  permissions: z.array(zPermission),
  user_id: z.string().nullish(),
});

export const zRedeemOnchainRequest = z.object({
  feerate: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  to_address: z.string(),
});

export const zRedeemOnchainResponse = z.object({
  txid: z.string(),
});

export const zRegisterLnAddressRequest = z.object({
  allows_nostr: z.boolean().optional(),
  nostr_pubkey: z.string().nullish(),
  username: z.string(),
  wallet_id: z.uuid().nullish(),
});

/**
 * Register Wallet Request
 */
export const zRegisterWalletRequest = z.object({
  user_id: z.string(),
});

/**
 * Send On-chain Payment Request
 */
export const zSendOnchainPaymentRequest = z.object({
  amount_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  feerate: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  recipient_address: z.string(),
});

/**
 * Send Payment Request
 */
export const zSendPaymentRequest = z.object({
  amount_msat: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  comment: z.string().nullish(),
  input: z.string(),
  wallet_id: z.uuid().nullish(),
});

/**
 * App setup info
 */
export const zSetupInfo = z.object({
  sign_up_complete: z.boolean(),
  welcome_complete: z.boolean(),
});

/**
 * Sign In Request
 */
export const zSignInRequest = z.object({
  password: z.string(),
});

/**
 * Sign In Response
 */
export const zSignInResponse = z.object({
  token: z.string(),
});

export const zSignMessageRequest = z.object({
  message: z.string(),
});

export const zSignMessageResponse = z.object({
  signature: z.string(),
});

/**
 * Sign Up Request
 */
export const zSignUpRequest = z.object({
  password: z.string(),
});

export const zUpdateLnAddressRequest = z.object({
  active: z.boolean().nullish(),
  allows_nostr: z.boolean().nullish(),
  nostr_pubkey: z.string().nullish(),
  username: z.string().nullish(),
});

/**
 * App version info
 */
export const zVersionInfo = z.object({
  build_time: z.string(),
  version: z.string(),
});

export const zWalletLnAddressResponse = z.object({
  ln_address: zLnAddress.nullish(),
});

export const zWalletOverview = z.object({
  balance: zBalance,
  created_at: z.iso.datetime(),
  id: z.uuid(),
  ln_address: zLnAddress.nullish(),
  n_contacts: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  n_invoices: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  n_payments: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  updated_at: z.iso.datetime().nullish(),
  user_id: z.string(),
});

export const zWalletResponse = z.object({
  balance: zBalance,
  contacts: z.array(zContact),
  created_at: z.iso.datetime(),
  id: z.uuid(),
  invoices: z.array(zInvoiceResponse),
  ln_address: zLnAddress.nullish(),
  payments: z.array(zPaymentResponse),
  updated_at: z.iso.datetime().nullish(),
  user_id: z.string(),
});

export const zWellKnownPath = z.object({
  username: z.string(),
});

/**
 * Found
 */
export const zWellKnownResponse = zLnUrlPayRequest;

export const zWellKnownNostrQuery = z.object({
  name: z.string().optional(),
});

/**
 * Found
 */
export const zWellKnownNostrResponse = zNostrNip05Response;

export const zCallbackPath = z.object({
  username: z.string(),
});

export const zCallbackQuery = z.object({
  amount: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  comment: z.string().nullish(),
});

/**
 * Found
 */
export const zCallbackResponse = zLnUrlCallbackResponse;

export const zRevokeApiKeysQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  user_id: z.string().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zRevokeApiKeysResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

export const zListApiKeysQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  user_id: z.string().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListApiKeysResponse = z.array(zApiKeyResponse);

export const zCreateApiKeyBody = zCreateApiKeyRequest;

/**
 * API Key Created
 */
export const zCreateApiKeyResponse = zApiKeyResponse;

export const zRevokeApiKeyPath = z.object({
  id: z.uuid(),
});

export const zGetApiKeyPath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetApiKeyResponse = zApiKeyResponse;

export const zSignInBody = zSignInRequest;

/**
 * Token Created
 */
export const zSignInResponse2 = zSignInResponse;

export const zSignUpBody = zSignUpRequest;

/**
 * Admin user created
 */
export const zSignUpResponse = zSignInResponse;

export const zDeleteInvoicesQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  status: zInvoiceStatus.nullish(),
  ledger: zLedger.nullish(),
  order_by: zInvoiceOrderBy.optional(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zDeleteInvoicesResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

export const zListInvoicesQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  status: zInvoiceStatus.nullish(),
  ledger: zLedger.nullish(),
  order_by: zInvoiceOrderBy.optional(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListInvoicesResponse = z.array(zInvoiceResponse);

export const zGenerateInvoiceBody = zNewInvoiceRequest;

/**
 * Invoice Created
 */
export const zGenerateInvoiceResponse = zInvoiceResponse;

export const zDeleteInvoicePath = z.object({
  id: z.uuid(),
});

export const zGetInvoicePath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetInvoiceResponse = zInvoiceResponse;

export const zDeleteAddressesQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  username: z.string().nullish(),
  active: z.boolean().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zDeleteAddressesResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

export const zListAddressesQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  username: z.string().nullish(),
  active: z.boolean().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListAddressesResponse = z.array(zLnAddress);

export const zRegisterAddressBody = zRegisterLnAddressRequest;

/**
 * LN Address Registered
 */
export const zRegisterAddressResponse = zLnAddress;

export const zDeleteAddressPath = z.object({
  id: z.uuid(),
});

export const zGetAddressPath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetAddressResponse = zLnAddress;

export const zUpdateAddressBody = zUpdateLnAddressRequest;

export const zUpdateAddressPath = z.object({
  id: z.uuid(),
});

/**
 * LN Address Updated
 */
export const zUpdateAddressResponse = zLnAddress;

/**
 * Found
 */
export const zGetUserWalletResponse = zWalletResponse;

export const zRevokeWalletApiKeysQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  user_id: z.string().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zRevokeWalletApiKeysResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

export const zListWalletApiKeysQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  user_id: z.string().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListWalletApiKeysResponse = z.array(zApiKeyResponse);

export const zCreateWalletApiKeyBody = zCreateApiKeyRequest;

/**
 * API Key Created
 */
export const zCreateWalletApiKeyResponse = zApiKeyResponse;

export const zRevokeWalletApiKeyPath = z.object({
  id: z.uuid(),
});

export const zGetWalletApiKeyPath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetWalletApiKeyResponse = zApiKeyResponse;

/**
 * Found
 */
export const zGetWalletBalanceResponse = zBalance;

/**
 * Success
 */
export const zListContactsResponse = z.array(zContact);

/**
 * Success
 */
export const zDeleteExpiredInvoicesResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

export const zListWalletInvoicesQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  status: zInvoiceStatus.nullish(),
  ledger: zLedger.nullish(),
  order_by: zInvoiceOrderBy.optional(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListWalletInvoicesResponse = z.array(zInvoiceResponse);

export const zNewWalletInvoiceBody = zNewInvoiceRequest;

/**
 * Invoice Created
 */
export const zNewWalletInvoiceResponse = zInvoiceResponse;

export const zGetWalletInvoicePath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetWalletInvoiceResponse = zInvoiceResponse;

/**
 * Found
 */
export const zGetWalletAddressResponse = zWalletLnAddressResponse;

export const zRegisterWalletAddressBody = zRegisterLnAddressRequest;

/**
 * LN Address Registered
 */
export const zRegisterWalletAddressResponse = zLnAddress;

export const zUpdateWalletAddressBody = zUpdateLnAddressRequest;

/**
 * LN Address Updated
 */
export const zUpdateWalletAddressResponse = zLnAddress;

/**
 * Success
 */
export const zDeleteFailedPaymentsResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

export const zListWalletPaymentsQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  status: zPaymentStatus.nullish(),
  ledger: zLedger.nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListWalletPaymentsResponse = z.array(zPaymentResponse);

export const zWalletPayBody = zSendPaymentRequest;

/**
 * Payment Sent
 */
export const zWalletPayResponse = zPaymentResponse;

export const zGetWalletPaymentPath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetWalletPaymentResponse = zPaymentResponse;

export const zDeletePaymentsQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  status: zPaymentStatus.nullish(),
  ledger: zLedger.nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zDeletePaymentsResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

export const zListPaymentsQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  wallet_id: z.uuid().nullish(),
  status: zPaymentStatus.nullish(),
  ledger: zLedger.nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zListPaymentsResponse = z.array(zPaymentResponse);

export const zPayBody = zSendPaymentRequest;

/**
 * Payment Sent
 */
export const zPayResponse = zPaymentResponse;

export const zDeletePaymentPath = z.object({
  id: z.uuid(),
});

export const zGetPaymentPath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetPaymentResponse = zPaymentResponse;

/**
 * OK
 */
export const zHealthCheckResponse = zHealthCheck;

/**
 * No Content on success
 */
export const zMarkWelcomeCompleteResponse = z.void();

/**
 * No Content on success
 */
export const zReadinessCheckResponse = z.void();

/**
 * OK
 */
export const zSetupCheckResponse = zSetupInfo;

/**
 * OK
 */
export const zVersionCheckResponse = zVersionInfo;

export const zDeleteWalletsQuery = z.object({
  limit: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  offset: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  ids: z.array(z.uuid()).nullish(),
  user_id: z.string().nullish(),
  order_direction: zOrderDirection.optional(),
});

/**
 * Success
 */
export const zDeleteWalletsResponse = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt('9223372036854775807'), {
    error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
  });

/**
 * Success
 */
export const zListWalletsResponse = z.array(zWalletResponse);

export const zRegisterWalletBody = zRegisterWalletRequest;

/**
 * Wallet Created
 */
export const zRegisterWalletResponse = zWalletResponse;

/**
 * Success
 */
export const zListWalletOverviewsResponse = z.array(zWalletOverview);

export const zDeleteWalletPath = z.object({
  id: z.uuid(),
});

export const zGetWalletPath = z.object({
  id: z.uuid(),
});

/**
 * Found
 */
export const zGetWalletResponse = zWalletResponse;
