//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
#![allow(dead_code)]

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_name: Option<String>,
    pub permissions: Json,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::account_preference::Entity")]
    AccountPreference,
    #[sea_orm(has_many = "super::api_key::Entity")]
    ApiKey,
    #[sea_orm(has_many = "super::auth_identity::Entity")]
    AuthIdentity,
}

impl Related<super::account_preference::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountPreference.def()
    }
}

impl Related<super::api_key::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKey.def()
    }
}

impl Related<super::auth_identity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthIdentity.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
