//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ln_address")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub wallet_id: Uuid,
    #[sea_orm(unique)]
    pub username: String,
    pub active: bool,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub allows_nostr: bool,
    pub nostr_pubkey: Option<String>,
    #[sea_orm(unique)]
    pub account_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Account,
    #[sea_orm(has_many = "super::invoice::Entity")]
    Invoice,
    // Codegen 1.1.19 duplicates AccountId here because it participates in both account and wallet FKs.
    #[sea_orm(
        belongs_to = "super::wallet::Entity",
        from = "(Column::AccountId, Column::WalletId)",
        to = "(super::wallet::Column::AccountId, super::wallet::Column::Id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Wallet,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::invoice::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invoice.def()
    }
}

impl Related<super::wallet::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wallet.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
