//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "local_credential")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: Uuid,
    #[sea_orm(unique)]
    pub identity_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub password_hash: Option<String>,
    pub enabled: bool,
    pub revision: Uuid,
    #[sea_orm(unique)]
    pub reset_hash: Option<String>,
    pub reset_expires_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Account,
    #[sea_orm(
        belongs_to = "super::auth_identity::Entity",
        from = "Column::IdentityId",
        to = "super::auth_identity::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AuthIdentity,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::auth_identity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthIdentity.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
