//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wallet")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub account_id: Uuid,
    pub asset_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub label: Option<String>,
    pub available_amount: i64,
    pub reserved_amount: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Account,
    #[sea_orm(
        belongs_to = "super::asset::Entity",
        from = "Column::AssetId",
        to = "super::asset::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Asset,
    #[sea_orm(has_many = "super::btc_address::Entity")]
    BtcAddress,
    #[sea_orm(has_many = "super::client_event::Entity")]
    ClientEvent,
    #[sea_orm(has_many = "super::invoice::Entity")]
    Invoice,
    #[sea_orm(has_one = "super::ln_address::Entity")]
    LnAddress,
    #[sea_orm(has_many = "super::payment::Entity")]
    Payment,
    #[sea_orm(has_many = "super::webhook_subscription::Entity")]
    WebhookSubscription,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::asset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Asset.def()
    }
}

impl Related<super::btc_address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BtcAddress.def()
    }
}

impl Related<super::client_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientEvent.def()
    }
}

impl Related<super::invoice::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invoice.def()
    }
}

impl Related<super::ln_address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LnAddress.def()
    }
}

impl Related<super::payment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Payment.def()
    }
}

impl Related<super::webhook_subscription::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebhookSubscription.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
