//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::lightning_addresses::Entity as LightningAddresses;
pub use super::lightning_invoices::Entity as LightningInvoices;
pub use super::lightning_payments::Entity as LightningPayments;
