name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      attestations: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (combined image)
        id: meta-app
        uses: docker/metadata-action@v5
        with:
          images: bitcoinnumeraire/swissknife

      - name: Extract metadata (server image)
        id: meta-server
        uses: docker/metadata-action@v5
        with:
          images: bitcoinnumeraire/swissknife-server

      - name: Extract metadata (dashboard image)
        id: meta-dashboard
        uses: docker/metadata-action@v5
        with:
          images: bitcoinnumeraire/swissknife-dashboard

      - name: Build and push combined Docker image
        id: push-app
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-app.outputs.tags }}
          labels: ${{ steps.meta-app.outputs.labels }}

      - name: Build and push backend Docker image
        id: push-server
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: swissknife-server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-server.outputs.tags }}
          labels: ${{ steps.meta-server.outputs.labels }}

      - name: Build and push dashboard Docker image
        id: push-dashboard
        uses: docker/build-push-action@v6
        with:
          context: ./dashboard
          file: ./dashboard/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-dashboard.outputs.tags }}
          labels: ${{ steps.meta-dashboard.outputs.labels }}

      - name: Generate artifact attestation (combined)
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: docker.io/bitcoinnumeraire/swissknife
          subject-digest: ${{ steps.push-app.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation (server)
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: docker.io/bitcoinnumeraire/swissknife-server
          subject-digest: ${{ steps.push-server.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation (dashboard)
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: docker.io/bitcoinnumeraire/swissknife-dashboard
          subject-digest: ${{ steps.push-dashboard.outputs.digest }}
          push-to-registry: true
